########
#
# Template for deploying the Cluster Operator.
#
# Parameters:
#   CLUSTER_OPERATOR_NAMESPACE: namespace to which to deploy the cluster operator. Defaults to "openshift-cluster-operator".
#   SERVING_CERT: base-64-encoded, pem cert to use for ssl communication with the Cluster Operator API Server. Required.
#   SERVING_KEY: base-64-encoded, pem private key for the cert to use for ssl communication with the Cluster Operator API Server. Required.
#   SERVING_CA: base-64-encoded, pem CA cert for the ssl certs. Required.
#   ANSIBLE_IMAGE: ansible image to use to run playbooks. Defaults to "fake-openshift-ansible:canary".
#   ANSIBLE_IMAGE_PULL_POLICY: policy to use to pull the ansible image. Always, Never, or IfNotPresent. Defaults to "Never".
#
########

apiVersion: v1
kind: Template
metadata:
  name: cluster-operator-deploy-template
  namespace: ${CLUSTER_OPERATOR_NAMESPACE}
objects:

# Service account for the API Server
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: co-apiserver
    namespace: ${CLUSTER_OPERATOR_NAMESPACE}

# Service account for the Controller Manager
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: co-controller-manager
    namespace: ${CLUSTER_OPERATOR_NAMESPACE}

# API Server gets the auth-delegator role to delegate auth decisions to
# the core API Server
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: "clusteroperator.openshift.io:apiserver-auth-delegator"
    namespace: ${CLUSTER_OPERATOR_NAMESPACE}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:auth-delegator
  subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: co-apiserver
    namespace: ${CLUSTER_OPERATOR_NAMESPACE}

# API Server gets the ability to read authentication. This allows it to
# read the specific configmap that has the requestheader-* entries to
# enable api aggregation
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: "clusteroperator.openshift.io:apiserver-authentication-reader"
    namespace: ${KUBE_SYSTEM_NAMESPACE}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: extension-apiserver-authentication-reader
  subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: co-apiserver
    namespace: ${CLUSTER_OPERATOR_NAMESPACE}

# Create a role for the Controller Manager to give it permissions to manage
# the resources of the clusteroperator
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: "clusteroperator.openshift.io:controller-manager"
  rules:
  # configmaps for leader election
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs:     ["create"]
  - apiGroups:     [""]
    resources:     ["configmaps"]
    resourceNames: ["co-controller-manager"]
    verbs: ["get","update"]
  # events for recording events
  - apiGroups: [""]
    resources: ["events"]
    verbs:     ["create","patch","update"]
  # allow all operations on all resources in our API group
  - apiGroups: ["clusteroperator.openshift.io"]
    resources: ["*"]
    verbs:     ["create", "get", "list", "watch", "update", "patch", "delete"]
  # allow operations on required resources in any namespace a cluster is created
  - apiGroups:     [""]
    resources:     ["configmaps", "pods", "secrets"]
    verbs: ["*"]
  - apiGroups:     ["batch"]
    resources:     ["jobs"]
    verbs: ["*"]

# Bind the Controller Manager service account to the role created for it
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: "clusteroperator.openshift.io:controller-manager"
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: "clusteroperator.openshift.io:controller-manager"
  subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: co-controller-manager
    namespace: ${CLUSTER_OPERATOR_NAMESPACE}

# Secret to pass the SSL certs to the API Server
- apiVersion: v1
  kind: Secret
  metadata:
    name: co-apiserver-cert
    namespace: ${CLUSTER_OPERATOR_NAMESPACE}
    labels:
      app: co-apiserver
  type: Opaque
  data:
    tls.crt: ${SERVING_CERT}
    tls.key: ${SERVING_KEY}

# Default secret for cluster SSL
- apiVersion: v1
  kind: Secret
  metadata:
    name: ssl-cert
    namespace: ${CLUSTER_OPERATOR_NAMESPACE}
  type: Opaque
  data:
    server.crt: ${SERVING_CERT}
    server.key: ${SERVING_KEY}
    ca.crt: ${SERVING_CA}

# Secret for AWS credentials to provision with.
# NOTE: likely will be replaced by a set of credentials per cluster
- apiVersion: v1
  kind: Secret
  metadata:
    name: aws-credentials
    namespace: ${CLUSTER_OPERATOR_NAMESPACE}
    labels:
      app: cluster-operator
  type: Opaque
  data:
    aws_access_key_id: ${AWS_ACCESS_KEY_ID}
    aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}

# Secret for AWS SSH private key
- apiVersion: v1
  kind: Secret
  metadata:
    name: ssh-private-key
    namespace: ${CLUSTER_OPERATOR_NAMESPACE}
    labels:
      app: cluster-operator
  type: Opaque
  data:
    ssh-privatekey: ${AWS_SSH_PRIVATE_KEY}

# Deployment of the API Server pod
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: co-apiserver
    namespace: ${CLUSTER_OPERATOR_NAMESPACE}
    labels:
      app: co-apiserver
  spec:
    selector:
      matchLabels:
        app: co-apiserver
    template:
      metadata:
        labels:
          app: co-apiserver
      spec:
        serviceAccountName: co-apiserver
        containers:
        - name: apiserver
          args:
          - apiserver
          - --secure-port
          - "6443"
          - --etcd-servers
          - http://localhost:2379
          - -v
          - "10"
          image: cluster-operator:canary
          command: ["/opt/services/cluster-operator"]
          imagePullPolicy: Never
          name: apiserver
          ports:
          - containerPort: 6443
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/run/openshift-cluster-operator
            name: apiserver-ssl
            readOnly: true
          readinessProbe:
            httpGet:
              port: 6443
              path: /healthz
              scheme: HTTPS
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              port: 6443
              path: /healthz
              scheme: HTTPS
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
        - name: etcd
          image: quay.io/coreos/etcd:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 20Mi
            limits:
              cpu: 100m
              memory: 30Mi
          env:
          - name: ETCD_DATA_DIR
            value: /etcd-data-dir
          command:
          - /usr/local/bin/etcd
          - --listen-client-urls
          - http://0.0.0.0:2379
          - --advertise-client-urls
          - http://localhost:2379
          ports:
          - containerPort: 2379
          volumeMounts:
          - name: etcd-data-dir
            mountPath: /etcd-data-dir
          readinessProbe:
            httpGet:
              port: 2379
              path: /health
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              port: 2379
              path: /health
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: apiserver-ssl
          secret:
            defaultMode: 420
            secretName: co-apiserver-cert
            items:
            - key: tls.crt
              path: apiserver.crt
            - key: tls.key
              path: apiserver.key
        - emptyDir: {}
          name: etcd-data-dir

# Deployment of the Controller Manager pod
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: co-controller-manager
    namespace: ${CLUSTER_OPERATOR_NAMESPACE}
    labels:
      app: co-controller-manager
  spec:
    selector:
      matchLabels:
        app: co-controller-manager
    template:
      metadata:
        labels:
          app: co-controller-manager
      spec:
        serviceAccountName: co-controller-manager
        containers:
        - name: controller-manager
          image: cluster-operator:canary
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 100m
              memory: 20Mi
            limits:
              cpu: 100m
              memory: 30Mi
          args:
          - controller-manager
          - --port
          - "8080"
          - --leader-election-namespace
          - ${CLUSTER_OPERATOR_NAMESPACE}
          - --leader-elect-resource-lock
          - "configmaps"
          - --profiling
          - "false"
          - --contention-profiling
          - "false"
          - -v
          - "1"
          - --log-level
          - "debug"
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthz
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2

# Service for the API Server
- kind: Service
  apiVersion: v1
  metadata:
    name: cluster-operator-apiserver
    namespace: ${CLUSTER_OPERATOR_NAMESPACE}
    labels:
      app: co-apiserver
  spec:
    type: NodePort
    selector:
      app: co-apiserver
    ports:
    - name: secure
      protocol: TCP
      port: 443
      targetPort: 6443
      nodePort: 30443

# Registration of the cluster-operator API with the aggregator
- apiVersion: apiregistration.k8s.io/v1beta1
  kind: APIService
  metadata:
    name: v1alpha1.clusteroperator.openshift.io
    namespace: ${KUBE_SYSTEM_NAMESPACE}
  spec:
    group: clusteroperator.openshift.io
    version: v1alpha1
    service:
      namespace: ${CLUSTER_OPERATOR_NAMESPACE}
      name: cluster-operator-apiserver
    caBundle: ${SERVING_CA}
    groupPriorityMinimum: 10000
    versionPriority: 20

parameters:
# Namespace to use for cluster-operator
- name: CLUSTER_OPERATOR_NAMESPACE
  value: openshift-cluster-operator
# Namespace of kube-system. Do not change.
- name: KUBE_SYSTEM_NAMESPACE
  value: kube-system
# CA cert for API Server SSL cert
- name: SERVING_CA
# Private key for API Server SSL cert
- name: SERVING_CERT
# Public API Server SSL cert
- name: SERVING_KEY
- name: AWS_ACCESS_KEY_ID
- name: AWS_SECRET_ACCESS_KEY
- name: AWS_SSH_PRIVATE_KEY
