// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	clusteroperator "github.com/openshift/cluster-operator/pkg/apis/clusteroperator"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_Cluster_To_clusteroperator_Cluster,
		Convert_clusteroperator_Cluster_To_v1alpha1_Cluster,
		Convert_v1alpha1_ClusterComputeNodeGroup_To_clusteroperator_ClusterComputeNodeGroup,
		Convert_clusteroperator_ClusterComputeNodeGroup_To_v1alpha1_ClusterComputeNodeGroup,
		Convert_v1alpha1_ClusterList_To_clusteroperator_ClusterList,
		Convert_clusteroperator_ClusterList_To_v1alpha1_ClusterList,
		Convert_v1alpha1_ClusterNodeGroup_To_clusteroperator_ClusterNodeGroup,
		Convert_clusteroperator_ClusterNodeGroup_To_v1alpha1_ClusterNodeGroup,
		Convert_v1alpha1_ClusterSpec_To_clusteroperator_ClusterSpec,
		Convert_clusteroperator_ClusterSpec_To_v1alpha1_ClusterSpec,
		Convert_v1alpha1_ClusterStatus_To_clusteroperator_ClusterStatus,
		Convert_clusteroperator_ClusterStatus_To_v1alpha1_ClusterStatus,
		Convert_v1alpha1_Node_To_clusteroperator_Node,
		Convert_clusteroperator_Node_To_v1alpha1_Node,
		Convert_v1alpha1_NodeGroup_To_clusteroperator_NodeGroup,
		Convert_clusteroperator_NodeGroup_To_v1alpha1_NodeGroup,
		Convert_v1alpha1_NodeGroupList_To_clusteroperator_NodeGroupList,
		Convert_clusteroperator_NodeGroupList_To_v1alpha1_NodeGroupList,
		Convert_v1alpha1_NodeGroupSpec_To_clusteroperator_NodeGroupSpec,
		Convert_clusteroperator_NodeGroupSpec_To_v1alpha1_NodeGroupSpec,
		Convert_v1alpha1_NodeGroupStatus_To_clusteroperator_NodeGroupStatus,
		Convert_clusteroperator_NodeGroupStatus_To_v1alpha1_NodeGroupStatus,
		Convert_v1alpha1_NodeList_To_clusteroperator_NodeList,
		Convert_clusteroperator_NodeList_To_v1alpha1_NodeList,
		Convert_v1alpha1_NodeSpec_To_clusteroperator_NodeSpec,
		Convert_clusteroperator_NodeSpec_To_v1alpha1_NodeSpec,
		Convert_v1alpha1_NodeStatus_To_clusteroperator_NodeStatus,
		Convert_clusteroperator_NodeStatus_To_v1alpha1_NodeStatus,
	)
}

func autoConvert_v1alpha1_Cluster_To_clusteroperator_Cluster(in *Cluster, out *clusteroperator.Cluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ClusterSpec_To_clusteroperator_ClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ClusterStatus_To_clusteroperator_ClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Cluster_To_clusteroperator_Cluster is an autogenerated conversion function.
func Convert_v1alpha1_Cluster_To_clusteroperator_Cluster(in *Cluster, out *clusteroperator.Cluster, s conversion.Scope) error {
	return autoConvert_v1alpha1_Cluster_To_clusteroperator_Cluster(in, out, s)
}

func autoConvert_clusteroperator_Cluster_To_v1alpha1_Cluster(in *clusteroperator.Cluster, out *Cluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_clusteroperator_ClusterSpec_To_v1alpha1_ClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_clusteroperator_ClusterStatus_To_v1alpha1_ClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_clusteroperator_Cluster_To_v1alpha1_Cluster is an autogenerated conversion function.
func Convert_clusteroperator_Cluster_To_v1alpha1_Cluster(in *clusteroperator.Cluster, out *Cluster, s conversion.Scope) error {
	return autoConvert_clusteroperator_Cluster_To_v1alpha1_Cluster(in, out, s)
}

func autoConvert_v1alpha1_ClusterComputeNodeGroup_To_clusteroperator_ClusterComputeNodeGroup(in *ClusterComputeNodeGroup, out *clusteroperator.ClusterComputeNodeGroup, s conversion.Scope) error {
	if err := Convert_v1alpha1_ClusterNodeGroup_To_clusteroperator_ClusterNodeGroup(&in.ClusterNodeGroup, &out.ClusterNodeGroup, s); err != nil {
		return err
	}
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_ClusterComputeNodeGroup_To_clusteroperator_ClusterComputeNodeGroup is an autogenerated conversion function.
func Convert_v1alpha1_ClusterComputeNodeGroup_To_clusteroperator_ClusterComputeNodeGroup(in *ClusterComputeNodeGroup, out *clusteroperator.ClusterComputeNodeGroup, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterComputeNodeGroup_To_clusteroperator_ClusterComputeNodeGroup(in, out, s)
}

func autoConvert_clusteroperator_ClusterComputeNodeGroup_To_v1alpha1_ClusterComputeNodeGroup(in *clusteroperator.ClusterComputeNodeGroup, out *ClusterComputeNodeGroup, s conversion.Scope) error {
	if err := Convert_clusteroperator_ClusterNodeGroup_To_v1alpha1_ClusterNodeGroup(&in.ClusterNodeGroup, &out.ClusterNodeGroup, s); err != nil {
		return err
	}
	out.Name = in.Name
	return nil
}

// Convert_clusteroperator_ClusterComputeNodeGroup_To_v1alpha1_ClusterComputeNodeGroup is an autogenerated conversion function.
func Convert_clusteroperator_ClusterComputeNodeGroup_To_v1alpha1_ClusterComputeNodeGroup(in *clusteroperator.ClusterComputeNodeGroup, out *ClusterComputeNodeGroup, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterComputeNodeGroup_To_v1alpha1_ClusterComputeNodeGroup(in, out, s)
}

func autoConvert_v1alpha1_ClusterList_To_clusteroperator_ClusterList(in *ClusterList, out *clusteroperator.ClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]clusteroperator.Cluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ClusterList_To_clusteroperator_ClusterList is an autogenerated conversion function.
func Convert_v1alpha1_ClusterList_To_clusteroperator_ClusterList(in *ClusterList, out *clusteroperator.ClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterList_To_clusteroperator_ClusterList(in, out, s)
}

func autoConvert_clusteroperator_ClusterList_To_v1alpha1_ClusterList(in *clusteroperator.ClusterList, out *ClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Cluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_clusteroperator_ClusterList_To_v1alpha1_ClusterList is an autogenerated conversion function.
func Convert_clusteroperator_ClusterList_To_v1alpha1_ClusterList(in *clusteroperator.ClusterList, out *ClusterList, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterList_To_v1alpha1_ClusterList(in, out, s)
}

func autoConvert_v1alpha1_ClusterNodeGroup_To_clusteroperator_ClusterNodeGroup(in *ClusterNodeGroup, out *clusteroperator.ClusterNodeGroup, s conversion.Scope) error {
	out.Size = in.Size
	return nil
}

// Convert_v1alpha1_ClusterNodeGroup_To_clusteroperator_ClusterNodeGroup is an autogenerated conversion function.
func Convert_v1alpha1_ClusterNodeGroup_To_clusteroperator_ClusterNodeGroup(in *ClusterNodeGroup, out *clusteroperator.ClusterNodeGroup, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterNodeGroup_To_clusteroperator_ClusterNodeGroup(in, out, s)
}

func autoConvert_clusteroperator_ClusterNodeGroup_To_v1alpha1_ClusterNodeGroup(in *clusteroperator.ClusterNodeGroup, out *ClusterNodeGroup, s conversion.Scope) error {
	out.Size = in.Size
	return nil
}

// Convert_clusteroperator_ClusterNodeGroup_To_v1alpha1_ClusterNodeGroup is an autogenerated conversion function.
func Convert_clusteroperator_ClusterNodeGroup_To_v1alpha1_ClusterNodeGroup(in *clusteroperator.ClusterNodeGroup, out *ClusterNodeGroup, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterNodeGroup_To_v1alpha1_ClusterNodeGroup(in, out, s)
}

func autoConvert_v1alpha1_ClusterSpec_To_clusteroperator_ClusterSpec(in *ClusterSpec, out *clusteroperator.ClusterSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ClusterNodeGroup_To_clusteroperator_ClusterNodeGroup(&in.MasterNodeGroup, &out.MasterNodeGroup, s); err != nil {
		return err
	}
	out.ComputeNodeGroups = *(*[]clusteroperator.ClusterComputeNodeGroup)(unsafe.Pointer(&in.ComputeNodeGroups))
	return nil
}

// Convert_v1alpha1_ClusterSpec_To_clusteroperator_ClusterSpec is an autogenerated conversion function.
func Convert_v1alpha1_ClusterSpec_To_clusteroperator_ClusterSpec(in *ClusterSpec, out *clusteroperator.ClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterSpec_To_clusteroperator_ClusterSpec(in, out, s)
}

func autoConvert_clusteroperator_ClusterSpec_To_v1alpha1_ClusterSpec(in *clusteroperator.ClusterSpec, out *ClusterSpec, s conversion.Scope) error {
	if err := Convert_clusteroperator_ClusterNodeGroup_To_v1alpha1_ClusterNodeGroup(&in.MasterNodeGroup, &out.MasterNodeGroup, s); err != nil {
		return err
	}
	out.ComputeNodeGroups = *(*[]ClusterComputeNodeGroup)(unsafe.Pointer(&in.ComputeNodeGroups))
	return nil
}

// Convert_clusteroperator_ClusterSpec_To_v1alpha1_ClusterSpec is an autogenerated conversion function.
func Convert_clusteroperator_ClusterSpec_To_v1alpha1_ClusterSpec(in *clusteroperator.ClusterSpec, out *ClusterSpec, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterSpec_To_v1alpha1_ClusterSpec(in, out, s)
}

func autoConvert_v1alpha1_ClusterStatus_To_clusteroperator_ClusterStatus(in *ClusterStatus, out *clusteroperator.ClusterStatus, s conversion.Scope) error {
	out.MasterNodeGroups = in.MasterNodeGroups
	out.ComputeNodeGroups = in.ComputeNodeGroups
	return nil
}

// Convert_v1alpha1_ClusterStatus_To_clusteroperator_ClusterStatus is an autogenerated conversion function.
func Convert_v1alpha1_ClusterStatus_To_clusteroperator_ClusterStatus(in *ClusterStatus, out *clusteroperator.ClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterStatus_To_clusteroperator_ClusterStatus(in, out, s)
}

func autoConvert_clusteroperator_ClusterStatus_To_v1alpha1_ClusterStatus(in *clusteroperator.ClusterStatus, out *ClusterStatus, s conversion.Scope) error {
	out.MasterNodeGroups = in.MasterNodeGroups
	out.ComputeNodeGroups = in.ComputeNodeGroups
	return nil
}

// Convert_clusteroperator_ClusterStatus_To_v1alpha1_ClusterStatus is an autogenerated conversion function.
func Convert_clusteroperator_ClusterStatus_To_v1alpha1_ClusterStatus(in *clusteroperator.ClusterStatus, out *ClusterStatus, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterStatus_To_v1alpha1_ClusterStatus(in, out, s)
}

func autoConvert_v1alpha1_Node_To_clusteroperator_Node(in *Node, out *clusteroperator.Node, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_NodeSpec_To_clusteroperator_NodeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_NodeStatus_To_clusteroperator_NodeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Node_To_clusteroperator_Node is an autogenerated conversion function.
func Convert_v1alpha1_Node_To_clusteroperator_Node(in *Node, out *clusteroperator.Node, s conversion.Scope) error {
	return autoConvert_v1alpha1_Node_To_clusteroperator_Node(in, out, s)
}

func autoConvert_clusteroperator_Node_To_v1alpha1_Node(in *clusteroperator.Node, out *Node, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_clusteroperator_NodeSpec_To_v1alpha1_NodeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_clusteroperator_NodeStatus_To_v1alpha1_NodeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_clusteroperator_Node_To_v1alpha1_Node is an autogenerated conversion function.
func Convert_clusteroperator_Node_To_v1alpha1_Node(in *clusteroperator.Node, out *Node, s conversion.Scope) error {
	return autoConvert_clusteroperator_Node_To_v1alpha1_Node(in, out, s)
}

func autoConvert_v1alpha1_NodeGroup_To_clusteroperator_NodeGroup(in *NodeGroup, out *clusteroperator.NodeGroup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_NodeGroupSpec_To_clusteroperator_NodeGroupSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_NodeGroupStatus_To_clusteroperator_NodeGroupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_NodeGroup_To_clusteroperator_NodeGroup is an autogenerated conversion function.
func Convert_v1alpha1_NodeGroup_To_clusteroperator_NodeGroup(in *NodeGroup, out *clusteroperator.NodeGroup, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeGroup_To_clusteroperator_NodeGroup(in, out, s)
}

func autoConvert_clusteroperator_NodeGroup_To_v1alpha1_NodeGroup(in *clusteroperator.NodeGroup, out *NodeGroup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_clusteroperator_NodeGroupSpec_To_v1alpha1_NodeGroupSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_clusteroperator_NodeGroupStatus_To_v1alpha1_NodeGroupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_clusteroperator_NodeGroup_To_v1alpha1_NodeGroup is an autogenerated conversion function.
func Convert_clusteroperator_NodeGroup_To_v1alpha1_NodeGroup(in *clusteroperator.NodeGroup, out *NodeGroup, s conversion.Scope) error {
	return autoConvert_clusteroperator_NodeGroup_To_v1alpha1_NodeGroup(in, out, s)
}

func autoConvert_v1alpha1_NodeGroupList_To_clusteroperator_NodeGroupList(in *NodeGroupList, out *clusteroperator.NodeGroupList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]clusteroperator.NodeGroup)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_NodeGroupList_To_clusteroperator_NodeGroupList is an autogenerated conversion function.
func Convert_v1alpha1_NodeGroupList_To_clusteroperator_NodeGroupList(in *NodeGroupList, out *clusteroperator.NodeGroupList, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeGroupList_To_clusteroperator_NodeGroupList(in, out, s)
}

func autoConvert_clusteroperator_NodeGroupList_To_v1alpha1_NodeGroupList(in *clusteroperator.NodeGroupList, out *NodeGroupList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]NodeGroup)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_clusteroperator_NodeGroupList_To_v1alpha1_NodeGroupList is an autogenerated conversion function.
func Convert_clusteroperator_NodeGroupList_To_v1alpha1_NodeGroupList(in *clusteroperator.NodeGroupList, out *NodeGroupList, s conversion.Scope) error {
	return autoConvert_clusteroperator_NodeGroupList_To_v1alpha1_NodeGroupList(in, out, s)
}

func autoConvert_v1alpha1_NodeGroupSpec_To_clusteroperator_NodeGroupSpec(in *NodeGroupSpec, out *clusteroperator.NodeGroupSpec, s conversion.Scope) error {
	out.NodeType = clusteroperator.NodeType(in.NodeType)
	out.Size = in.Size
	return nil
}

// Convert_v1alpha1_NodeGroupSpec_To_clusteroperator_NodeGroupSpec is an autogenerated conversion function.
func Convert_v1alpha1_NodeGroupSpec_To_clusteroperator_NodeGroupSpec(in *NodeGroupSpec, out *clusteroperator.NodeGroupSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeGroupSpec_To_clusteroperator_NodeGroupSpec(in, out, s)
}

func autoConvert_clusteroperator_NodeGroupSpec_To_v1alpha1_NodeGroupSpec(in *clusteroperator.NodeGroupSpec, out *NodeGroupSpec, s conversion.Scope) error {
	out.NodeType = NodeType(in.NodeType)
	out.Size = in.Size
	return nil
}

// Convert_clusteroperator_NodeGroupSpec_To_v1alpha1_NodeGroupSpec is an autogenerated conversion function.
func Convert_clusteroperator_NodeGroupSpec_To_v1alpha1_NodeGroupSpec(in *clusteroperator.NodeGroupSpec, out *NodeGroupSpec, s conversion.Scope) error {
	return autoConvert_clusteroperator_NodeGroupSpec_To_v1alpha1_NodeGroupSpec(in, out, s)
}

func autoConvert_v1alpha1_NodeGroupStatus_To_clusteroperator_NodeGroupStatus(in *NodeGroupStatus, out *clusteroperator.NodeGroupStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_NodeGroupStatus_To_clusteroperator_NodeGroupStatus is an autogenerated conversion function.
func Convert_v1alpha1_NodeGroupStatus_To_clusteroperator_NodeGroupStatus(in *NodeGroupStatus, out *clusteroperator.NodeGroupStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeGroupStatus_To_clusteroperator_NodeGroupStatus(in, out, s)
}

func autoConvert_clusteroperator_NodeGroupStatus_To_v1alpha1_NodeGroupStatus(in *clusteroperator.NodeGroupStatus, out *NodeGroupStatus, s conversion.Scope) error {
	return nil
}

// Convert_clusteroperator_NodeGroupStatus_To_v1alpha1_NodeGroupStatus is an autogenerated conversion function.
func Convert_clusteroperator_NodeGroupStatus_To_v1alpha1_NodeGroupStatus(in *clusteroperator.NodeGroupStatus, out *NodeGroupStatus, s conversion.Scope) error {
	return autoConvert_clusteroperator_NodeGroupStatus_To_v1alpha1_NodeGroupStatus(in, out, s)
}

func autoConvert_v1alpha1_NodeList_To_clusteroperator_NodeList(in *NodeList, out *clusteroperator.NodeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]clusteroperator.Node)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_NodeList_To_clusteroperator_NodeList is an autogenerated conversion function.
func Convert_v1alpha1_NodeList_To_clusteroperator_NodeList(in *NodeList, out *clusteroperator.NodeList, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeList_To_clusteroperator_NodeList(in, out, s)
}

func autoConvert_clusteroperator_NodeList_To_v1alpha1_NodeList(in *clusteroperator.NodeList, out *NodeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Node)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_clusteroperator_NodeList_To_v1alpha1_NodeList is an autogenerated conversion function.
func Convert_clusteroperator_NodeList_To_v1alpha1_NodeList(in *clusteroperator.NodeList, out *NodeList, s conversion.Scope) error {
	return autoConvert_clusteroperator_NodeList_To_v1alpha1_NodeList(in, out, s)
}

func autoConvert_v1alpha1_NodeSpec_To_clusteroperator_NodeSpec(in *NodeSpec, out *clusteroperator.NodeSpec, s conversion.Scope) error {
	out.NodeGroupName = in.NodeGroupName
	out.NodeType = clusteroperator.NodeType(in.NodeType)
	return nil
}

// Convert_v1alpha1_NodeSpec_To_clusteroperator_NodeSpec is an autogenerated conversion function.
func Convert_v1alpha1_NodeSpec_To_clusteroperator_NodeSpec(in *NodeSpec, out *clusteroperator.NodeSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeSpec_To_clusteroperator_NodeSpec(in, out, s)
}

func autoConvert_clusteroperator_NodeSpec_To_v1alpha1_NodeSpec(in *clusteroperator.NodeSpec, out *NodeSpec, s conversion.Scope) error {
	out.NodeGroupName = in.NodeGroupName
	out.NodeType = NodeType(in.NodeType)
	return nil
}

// Convert_clusteroperator_NodeSpec_To_v1alpha1_NodeSpec is an autogenerated conversion function.
func Convert_clusteroperator_NodeSpec_To_v1alpha1_NodeSpec(in *clusteroperator.NodeSpec, out *NodeSpec, s conversion.Scope) error {
	return autoConvert_clusteroperator_NodeSpec_To_v1alpha1_NodeSpec(in, out, s)
}

func autoConvert_v1alpha1_NodeStatus_To_clusteroperator_NodeStatus(in *NodeStatus, out *clusteroperator.NodeStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_NodeStatus_To_clusteroperator_NodeStatus is an autogenerated conversion function.
func Convert_v1alpha1_NodeStatus_To_clusteroperator_NodeStatus(in *NodeStatus, out *clusteroperator.NodeStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeStatus_To_clusteroperator_NodeStatus(in, out, s)
}

func autoConvert_clusteroperator_NodeStatus_To_v1alpha1_NodeStatus(in *clusteroperator.NodeStatus, out *NodeStatus, s conversion.Scope) error {
	return nil
}

// Convert_clusteroperator_NodeStatus_To_v1alpha1_NodeStatus is an autogenerated conversion function.
func Convert_clusteroperator_NodeStatus_To_v1alpha1_NodeStatus(in *clusteroperator.NodeStatus, out *NodeStatus, s conversion.Scope) error {
	return autoConvert_clusteroperator_NodeStatus_To_v1alpha1_NodeStatus(in, out, s)
}
