// +build !ignore_autogenerated

/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	clusteroperator "github.com/openshift/cluster-operator/pkg/apis/clusteroperator"
	core_v1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_AWSClusterSpec_To_clusteroperator_AWSClusterSpec,
		Convert_clusteroperator_AWSClusterSpec_To_v1alpha1_AWSClusterSpec,
		Convert_v1alpha1_AWSMachineProviderStatus_To_clusteroperator_AWSMachineProviderStatus,
		Convert_clusteroperator_AWSMachineProviderStatus_To_v1alpha1_AWSMachineProviderStatus,
		Convert_v1alpha1_AWSRegionAMIs_To_clusteroperator_AWSRegionAMIs,
		Convert_clusteroperator_AWSRegionAMIs_To_v1alpha1_AWSRegionAMIs,
		Convert_v1alpha1_AWSVMImages_To_clusteroperator_AWSVMImages,
		Convert_clusteroperator_AWSVMImages_To_v1alpha1_AWSVMImages,
		Convert_v1alpha1_ClusterCondition_To_clusteroperator_ClusterCondition,
		Convert_clusteroperator_ClusterCondition_To_v1alpha1_ClusterCondition,
		Convert_v1alpha1_ClusterConfigSpec_To_clusteroperator_ClusterConfigSpec,
		Convert_clusteroperator_ClusterConfigSpec_To_v1alpha1_ClusterConfigSpec,
		Convert_v1alpha1_ClusterDeployment_To_clusteroperator_ClusterDeployment,
		Convert_clusteroperator_ClusterDeployment_To_v1alpha1_ClusterDeployment,
		Convert_v1alpha1_ClusterDeploymentList_To_clusteroperator_ClusterDeploymentList,
		Convert_clusteroperator_ClusterDeploymentList_To_v1alpha1_ClusterDeploymentList,
		Convert_v1alpha1_ClusterDeploymentSpec_To_clusteroperator_ClusterDeploymentSpec,
		Convert_clusteroperator_ClusterDeploymentSpec_To_v1alpha1_ClusterDeploymentSpec,
		Convert_v1alpha1_ClusterDeploymentStatus_To_clusteroperator_ClusterDeploymentStatus,
		Convert_clusteroperator_ClusterDeploymentStatus_To_v1alpha1_ClusterDeploymentStatus,
		Convert_v1alpha1_ClusterHardwareSpec_To_clusteroperator_ClusterHardwareSpec,
		Convert_clusteroperator_ClusterHardwareSpec_To_v1alpha1_ClusterHardwareSpec,
		Convert_v1alpha1_ClusterMachineSet_To_clusteroperator_ClusterMachineSet,
		Convert_clusteroperator_ClusterMachineSet_To_v1alpha1_ClusterMachineSet,
		Convert_v1alpha1_ClusterProviderConfigSpec_To_clusteroperator_ClusterProviderConfigSpec,
		Convert_clusteroperator_ClusterProviderConfigSpec_To_v1alpha1_ClusterProviderConfigSpec,
		Convert_v1alpha1_ClusterProviderStatus_To_clusteroperator_ClusterProviderStatus,
		Convert_clusteroperator_ClusterProviderStatus_To_v1alpha1_ClusterProviderStatus,
		Convert_v1alpha1_ClusterVersion_To_clusteroperator_ClusterVersion,
		Convert_clusteroperator_ClusterVersion_To_v1alpha1_ClusterVersion,
		Convert_v1alpha1_ClusterVersionList_To_clusteroperator_ClusterVersionList,
		Convert_clusteroperator_ClusterVersionList_To_v1alpha1_ClusterVersionList,
		Convert_v1alpha1_ClusterVersionReference_To_clusteroperator_ClusterVersionReference,
		Convert_clusteroperator_ClusterVersionReference_To_v1alpha1_ClusterVersionReference,
		Convert_v1alpha1_ClusterVersionSpec_To_clusteroperator_ClusterVersionSpec,
		Convert_clusteroperator_ClusterVersionSpec_To_v1alpha1_ClusterVersionSpec,
		Convert_v1alpha1_ClusterVersionStatus_To_clusteroperator_ClusterVersionStatus,
		Convert_clusteroperator_ClusterVersionStatus_To_v1alpha1_ClusterVersionStatus,
		Convert_v1alpha1_MachineSetAWSHardwareSpec_To_clusteroperator_MachineSetAWSHardwareSpec,
		Convert_clusteroperator_MachineSetAWSHardwareSpec_To_v1alpha1_MachineSetAWSHardwareSpec,
		Convert_v1alpha1_MachineSetConfig_To_clusteroperator_MachineSetConfig,
		Convert_clusteroperator_MachineSetConfig_To_v1alpha1_MachineSetConfig,
		Convert_v1alpha1_MachineSetHardwareSpec_To_clusteroperator_MachineSetHardwareSpec,
		Convert_clusteroperator_MachineSetHardwareSpec_To_v1alpha1_MachineSetHardwareSpec,
		Convert_v1alpha1_MachineSetProviderConfigSpec_To_clusteroperator_MachineSetProviderConfigSpec,
		Convert_clusteroperator_MachineSetProviderConfigSpec_To_v1alpha1_MachineSetProviderConfigSpec,
		Convert_v1alpha1_MachineSetSpec_To_clusteroperator_MachineSetSpec,
		Convert_clusteroperator_MachineSetSpec_To_v1alpha1_MachineSetSpec,
		Convert_v1alpha1_VMImage_To_clusteroperator_VMImage,
		Convert_clusteroperator_VMImage_To_v1alpha1_VMImage,
		Convert_v1alpha1_VMImages_To_clusteroperator_VMImages,
		Convert_clusteroperator_VMImages_To_v1alpha1_VMImages,
	)
}

func autoConvert_v1alpha1_AWSClusterSpec_To_clusteroperator_AWSClusterSpec(in *AWSClusterSpec, out *clusteroperator.AWSClusterSpec, s conversion.Scope) error {
	out.AccountSecret = in.AccountSecret
	out.SSHSecret = in.SSHSecret
	out.SSHUser = in.SSHUser
	out.SSLSecret = in.SSLSecret
	out.KeyPairName = in.KeyPairName
	out.Region = in.Region
	out.VPCName = in.VPCName
	out.VPCSubnet = in.VPCSubnet
	return nil
}

// Convert_v1alpha1_AWSClusterSpec_To_clusteroperator_AWSClusterSpec is an autogenerated conversion function.
func Convert_v1alpha1_AWSClusterSpec_To_clusteroperator_AWSClusterSpec(in *AWSClusterSpec, out *clusteroperator.AWSClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_AWSClusterSpec_To_clusteroperator_AWSClusterSpec(in, out, s)
}

func autoConvert_clusteroperator_AWSClusterSpec_To_v1alpha1_AWSClusterSpec(in *clusteroperator.AWSClusterSpec, out *AWSClusterSpec, s conversion.Scope) error {
	out.AccountSecret = in.AccountSecret
	out.SSHSecret = in.SSHSecret
	out.SSHUser = in.SSHUser
	out.SSLSecret = in.SSLSecret
	out.KeyPairName = in.KeyPairName
	out.Region = in.Region
	out.VPCName = in.VPCName
	out.VPCSubnet = in.VPCSubnet
	return nil
}

// Convert_clusteroperator_AWSClusterSpec_To_v1alpha1_AWSClusterSpec is an autogenerated conversion function.
func Convert_clusteroperator_AWSClusterSpec_To_v1alpha1_AWSClusterSpec(in *clusteroperator.AWSClusterSpec, out *AWSClusterSpec, s conversion.Scope) error {
	return autoConvert_clusteroperator_AWSClusterSpec_To_v1alpha1_AWSClusterSpec(in, out, s)
}

func autoConvert_v1alpha1_AWSMachineProviderStatus_To_clusteroperator_AWSMachineProviderStatus(in *AWSMachineProviderStatus, out *clusteroperator.AWSMachineProviderStatus, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.InstanceID = (*string)(unsafe.Pointer(in.InstanceID))
	out.InstanceState = (*string)(unsafe.Pointer(in.InstanceState))
	out.PublicIP = (*string)(unsafe.Pointer(in.PublicIP))
	out.PrivateIP = (*string)(unsafe.Pointer(in.PrivateIP))
	out.PublicDNS = (*string)(unsafe.Pointer(in.PublicDNS))
	out.PrivateDNS = (*string)(unsafe.Pointer(in.PrivateDNS))
	out.LastELBSync = (*v1.Time)(unsafe.Pointer(in.LastELBSync))
	out.LastELBSyncGeneration = in.LastELBSyncGeneration
	return nil
}

// Convert_v1alpha1_AWSMachineProviderStatus_To_clusteroperator_AWSMachineProviderStatus is an autogenerated conversion function.
func Convert_v1alpha1_AWSMachineProviderStatus_To_clusteroperator_AWSMachineProviderStatus(in *AWSMachineProviderStatus, out *clusteroperator.AWSMachineProviderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_AWSMachineProviderStatus_To_clusteroperator_AWSMachineProviderStatus(in, out, s)
}

func autoConvert_clusteroperator_AWSMachineProviderStatus_To_v1alpha1_AWSMachineProviderStatus(in *clusteroperator.AWSMachineProviderStatus, out *AWSMachineProviderStatus, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.InstanceID = (*string)(unsafe.Pointer(in.InstanceID))
	out.InstanceState = (*string)(unsafe.Pointer(in.InstanceState))
	out.PublicIP = (*string)(unsafe.Pointer(in.PublicIP))
	out.PrivateIP = (*string)(unsafe.Pointer(in.PrivateIP))
	out.PublicDNS = (*string)(unsafe.Pointer(in.PublicDNS))
	out.PrivateDNS = (*string)(unsafe.Pointer(in.PrivateDNS))
	out.LastELBSync = (*v1.Time)(unsafe.Pointer(in.LastELBSync))
	out.LastELBSyncGeneration = in.LastELBSyncGeneration
	return nil
}

// Convert_clusteroperator_AWSMachineProviderStatus_To_v1alpha1_AWSMachineProviderStatus is an autogenerated conversion function.
func Convert_clusteroperator_AWSMachineProviderStatus_To_v1alpha1_AWSMachineProviderStatus(in *clusteroperator.AWSMachineProviderStatus, out *AWSMachineProviderStatus, s conversion.Scope) error {
	return autoConvert_clusteroperator_AWSMachineProviderStatus_To_v1alpha1_AWSMachineProviderStatus(in, out, s)
}

func autoConvert_v1alpha1_AWSRegionAMIs_To_clusteroperator_AWSRegionAMIs(in *AWSRegionAMIs, out *clusteroperator.AWSRegionAMIs, s conversion.Scope) error {
	out.Region = in.Region
	out.AMI = in.AMI
	out.MasterAMI = (*string)(unsafe.Pointer(in.MasterAMI))
	return nil
}

// Convert_v1alpha1_AWSRegionAMIs_To_clusteroperator_AWSRegionAMIs is an autogenerated conversion function.
func Convert_v1alpha1_AWSRegionAMIs_To_clusteroperator_AWSRegionAMIs(in *AWSRegionAMIs, out *clusteroperator.AWSRegionAMIs, s conversion.Scope) error {
	return autoConvert_v1alpha1_AWSRegionAMIs_To_clusteroperator_AWSRegionAMIs(in, out, s)
}

func autoConvert_clusteroperator_AWSRegionAMIs_To_v1alpha1_AWSRegionAMIs(in *clusteroperator.AWSRegionAMIs, out *AWSRegionAMIs, s conversion.Scope) error {
	out.Region = in.Region
	out.AMI = in.AMI
	out.MasterAMI = (*string)(unsafe.Pointer(in.MasterAMI))
	return nil
}

// Convert_clusteroperator_AWSRegionAMIs_To_v1alpha1_AWSRegionAMIs is an autogenerated conversion function.
func Convert_clusteroperator_AWSRegionAMIs_To_v1alpha1_AWSRegionAMIs(in *clusteroperator.AWSRegionAMIs, out *AWSRegionAMIs, s conversion.Scope) error {
	return autoConvert_clusteroperator_AWSRegionAMIs_To_v1alpha1_AWSRegionAMIs(in, out, s)
}

func autoConvert_v1alpha1_AWSVMImages_To_clusteroperator_AWSVMImages(in *AWSVMImages, out *clusteroperator.AWSVMImages, s conversion.Scope) error {
	out.RegionAMIs = *(*[]clusteroperator.AWSRegionAMIs)(unsafe.Pointer(&in.RegionAMIs))
	return nil
}

// Convert_v1alpha1_AWSVMImages_To_clusteroperator_AWSVMImages is an autogenerated conversion function.
func Convert_v1alpha1_AWSVMImages_To_clusteroperator_AWSVMImages(in *AWSVMImages, out *clusteroperator.AWSVMImages, s conversion.Scope) error {
	return autoConvert_v1alpha1_AWSVMImages_To_clusteroperator_AWSVMImages(in, out, s)
}

func autoConvert_clusteroperator_AWSVMImages_To_v1alpha1_AWSVMImages(in *clusteroperator.AWSVMImages, out *AWSVMImages, s conversion.Scope) error {
	out.RegionAMIs = *(*[]AWSRegionAMIs)(unsafe.Pointer(&in.RegionAMIs))
	return nil
}

// Convert_clusteroperator_AWSVMImages_To_v1alpha1_AWSVMImages is an autogenerated conversion function.
func Convert_clusteroperator_AWSVMImages_To_v1alpha1_AWSVMImages(in *clusteroperator.AWSVMImages, out *AWSVMImages, s conversion.Scope) error {
	return autoConvert_clusteroperator_AWSVMImages_To_v1alpha1_AWSVMImages(in, out, s)
}

func autoConvert_v1alpha1_ClusterCondition_To_clusteroperator_ClusterCondition(in *ClusterCondition, out *clusteroperator.ClusterCondition, s conversion.Scope) error {
	out.Type = clusteroperator.ClusterConditionType(in.Type)
	out.Status = core_v1.ConditionStatus(in.Status)
	out.LastProbeTime = in.LastProbeTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha1_ClusterCondition_To_clusteroperator_ClusterCondition is an autogenerated conversion function.
func Convert_v1alpha1_ClusterCondition_To_clusteroperator_ClusterCondition(in *ClusterCondition, out *clusteroperator.ClusterCondition, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterCondition_To_clusteroperator_ClusterCondition(in, out, s)
}

func autoConvert_clusteroperator_ClusterCondition_To_v1alpha1_ClusterCondition(in *clusteroperator.ClusterCondition, out *ClusterCondition, s conversion.Scope) error {
	out.Type = ClusterConditionType(in.Type)
	out.Status = core_v1.ConditionStatus(in.Status)
	out.LastProbeTime = in.LastProbeTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_clusteroperator_ClusterCondition_To_v1alpha1_ClusterCondition is an autogenerated conversion function.
func Convert_clusteroperator_ClusterCondition_To_v1alpha1_ClusterCondition(in *clusteroperator.ClusterCondition, out *ClusterCondition, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterCondition_To_v1alpha1_ClusterCondition(in, out, s)
}

func autoConvert_v1alpha1_ClusterConfigSpec_To_clusteroperator_ClusterConfigSpec(in *ClusterConfigSpec, out *clusteroperator.ClusterConfigSpec, s conversion.Scope) error {
	out.SDNPluginName = in.SDNPluginName
	out.ServiceNetworkSubnet = in.ServiceNetworkSubnet
	out.PodNetworkSubnet = in.PodNetworkSubnet
	return nil
}

// Convert_v1alpha1_ClusterConfigSpec_To_clusteroperator_ClusterConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_ClusterConfigSpec_To_clusteroperator_ClusterConfigSpec(in *ClusterConfigSpec, out *clusteroperator.ClusterConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterConfigSpec_To_clusteroperator_ClusterConfigSpec(in, out, s)
}

func autoConvert_clusteroperator_ClusterConfigSpec_To_v1alpha1_ClusterConfigSpec(in *clusteroperator.ClusterConfigSpec, out *ClusterConfigSpec, s conversion.Scope) error {
	out.SDNPluginName = in.SDNPluginName
	out.ServiceNetworkSubnet = in.ServiceNetworkSubnet
	out.PodNetworkSubnet = in.PodNetworkSubnet
	return nil
}

// Convert_clusteroperator_ClusterConfigSpec_To_v1alpha1_ClusterConfigSpec is an autogenerated conversion function.
func Convert_clusteroperator_ClusterConfigSpec_To_v1alpha1_ClusterConfigSpec(in *clusteroperator.ClusterConfigSpec, out *ClusterConfigSpec, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterConfigSpec_To_v1alpha1_ClusterConfigSpec(in, out, s)
}

func autoConvert_v1alpha1_ClusterDeployment_To_clusteroperator_ClusterDeployment(in *ClusterDeployment, out *clusteroperator.ClusterDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ClusterDeploymentSpec_To_clusteroperator_ClusterDeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ClusterDeploymentStatus_To_clusteroperator_ClusterDeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ClusterDeployment_To_clusteroperator_ClusterDeployment is an autogenerated conversion function.
func Convert_v1alpha1_ClusterDeployment_To_clusteroperator_ClusterDeployment(in *ClusterDeployment, out *clusteroperator.ClusterDeployment, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterDeployment_To_clusteroperator_ClusterDeployment(in, out, s)
}

func autoConvert_clusteroperator_ClusterDeployment_To_v1alpha1_ClusterDeployment(in *clusteroperator.ClusterDeployment, out *ClusterDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_clusteroperator_ClusterDeploymentSpec_To_v1alpha1_ClusterDeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_clusteroperator_ClusterDeploymentStatus_To_v1alpha1_ClusterDeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_clusteroperator_ClusterDeployment_To_v1alpha1_ClusterDeployment is an autogenerated conversion function.
func Convert_clusteroperator_ClusterDeployment_To_v1alpha1_ClusterDeployment(in *clusteroperator.ClusterDeployment, out *ClusterDeployment, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterDeployment_To_v1alpha1_ClusterDeployment(in, out, s)
}

func autoConvert_v1alpha1_ClusterDeploymentList_To_clusteroperator_ClusterDeploymentList(in *ClusterDeploymentList, out *clusteroperator.ClusterDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]clusteroperator.ClusterDeployment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ClusterDeploymentList_To_clusteroperator_ClusterDeploymentList is an autogenerated conversion function.
func Convert_v1alpha1_ClusterDeploymentList_To_clusteroperator_ClusterDeploymentList(in *ClusterDeploymentList, out *clusteroperator.ClusterDeploymentList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterDeploymentList_To_clusteroperator_ClusterDeploymentList(in, out, s)
}

func autoConvert_clusteroperator_ClusterDeploymentList_To_v1alpha1_ClusterDeploymentList(in *clusteroperator.ClusterDeploymentList, out *ClusterDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ClusterDeployment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_clusteroperator_ClusterDeploymentList_To_v1alpha1_ClusterDeploymentList is an autogenerated conversion function.
func Convert_clusteroperator_ClusterDeploymentList_To_v1alpha1_ClusterDeploymentList(in *clusteroperator.ClusterDeploymentList, out *ClusterDeploymentList, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterDeploymentList_To_v1alpha1_ClusterDeploymentList(in, out, s)
}

func autoConvert_v1alpha1_ClusterDeploymentSpec_To_clusteroperator_ClusterDeploymentSpec(in *ClusterDeploymentSpec, out *clusteroperator.ClusterDeploymentSpec, s conversion.Scope) error {
	out.ClusterID = in.ClusterID
	if err := Convert_v1alpha1_ClusterHardwareSpec_To_clusteroperator_ClusterHardwareSpec(&in.Hardware, &out.Hardware, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ClusterConfigSpec_To_clusteroperator_ClusterConfigSpec(&in.Config, &out.Config, s); err != nil {
		return err
	}
	out.DefaultHardwareSpec = (*clusteroperator.MachineSetHardwareSpec)(unsafe.Pointer(in.DefaultHardwareSpec))
	out.MachineSets = *(*[]clusteroperator.ClusterMachineSet)(unsafe.Pointer(&in.MachineSets))
	if err := Convert_v1alpha1_ClusterVersionReference_To_clusteroperator_ClusterVersionReference(&in.ClusterVersionRef, &out.ClusterVersionRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ClusterDeploymentSpec_To_clusteroperator_ClusterDeploymentSpec is an autogenerated conversion function.
func Convert_v1alpha1_ClusterDeploymentSpec_To_clusteroperator_ClusterDeploymentSpec(in *ClusterDeploymentSpec, out *clusteroperator.ClusterDeploymentSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterDeploymentSpec_To_clusteroperator_ClusterDeploymentSpec(in, out, s)
}

func autoConvert_clusteroperator_ClusterDeploymentSpec_To_v1alpha1_ClusterDeploymentSpec(in *clusteroperator.ClusterDeploymentSpec, out *ClusterDeploymentSpec, s conversion.Scope) error {
	out.ClusterID = in.ClusterID
	if err := Convert_clusteroperator_ClusterHardwareSpec_To_v1alpha1_ClusterHardwareSpec(&in.Hardware, &out.Hardware, s); err != nil {
		return err
	}
	if err := Convert_clusteroperator_ClusterConfigSpec_To_v1alpha1_ClusterConfigSpec(&in.Config, &out.Config, s); err != nil {
		return err
	}
	out.DefaultHardwareSpec = (*MachineSetHardwareSpec)(unsafe.Pointer(in.DefaultHardwareSpec))
	out.MachineSets = *(*[]ClusterMachineSet)(unsafe.Pointer(&in.MachineSets))
	if err := Convert_clusteroperator_ClusterVersionReference_To_v1alpha1_ClusterVersionReference(&in.ClusterVersionRef, &out.ClusterVersionRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_clusteroperator_ClusterDeploymentSpec_To_v1alpha1_ClusterDeploymentSpec is an autogenerated conversion function.
func Convert_clusteroperator_ClusterDeploymentSpec_To_v1alpha1_ClusterDeploymentSpec(in *clusteroperator.ClusterDeploymentSpec, out *ClusterDeploymentSpec, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterDeploymentSpec_To_v1alpha1_ClusterDeploymentSpec(in, out, s)
}

func autoConvert_v1alpha1_ClusterDeploymentStatus_To_clusteroperator_ClusterDeploymentStatus(in *ClusterDeploymentStatus, out *clusteroperator.ClusterDeploymentStatus, s conversion.Scope) error {
	out.MachineSetCount = in.MachineSetCount
	out.MasterMachineSetName = in.MasterMachineSetName
	out.InfraMachineSetName = in.InfraMachineSetName
	out.AdminKubeconfig = (*core_v1.LocalObjectReference)(unsafe.Pointer(in.AdminKubeconfig))
	out.Provisioned = in.Provisioned
	out.ProvisionedJobGeneration = in.ProvisionedJobGeneration
	out.ControlPlaneInstalled = in.ControlPlaneInstalled
	out.ControlPlaneInstalledJobClusterGeneration = in.ControlPlaneInstalledJobClusterGeneration
	out.ControlPlaneInstalledJobMachineSetGeneration = in.ControlPlaneInstalledJobMachineSetGeneration
	out.ComponentsInstalled = in.ComponentsInstalled
	out.ComponentsInstalledJobClusterGeneration = in.ComponentsInstalledJobClusterGeneration
	out.ComponentsInstalledJobMachineSetGeneration = in.ComponentsInstalledJobMachineSetGeneration
	out.NodeConfigInstalled = in.NodeConfigInstalled
	out.NodeConfigInstalledJobClusterGeneration = in.NodeConfigInstalledJobClusterGeneration
	out.NodeConfigInstalledJobMachineSetGeneration = in.NodeConfigInstalledJobMachineSetGeneration
	out.NodeConfigInstalledTime = (*v1.Time)(unsafe.Pointer(in.NodeConfigInstalledTime))
	out.ClusterAPIInstalled = in.ClusterAPIInstalled
	out.ClusterAPIInstalledJobClusterGeneration = in.ClusterAPIInstalledJobClusterGeneration
	out.ClusterAPIInstalledJobMachineSetGeneration = in.ClusterAPIInstalledJobMachineSetGeneration
	out.ClusterAPIInstalledTime = (*v1.Time)(unsafe.Pointer(in.ClusterAPIInstalledTime))
	out.Ready = in.Ready
	out.Conditions = *(*[]clusteroperator.ClusterCondition)(unsafe.Pointer(&in.Conditions))
	out.ClusterVersionRef = (*core_v1.ObjectReference)(unsafe.Pointer(in.ClusterVersionRef))
	return nil
}

// Convert_v1alpha1_ClusterDeploymentStatus_To_clusteroperator_ClusterDeploymentStatus is an autogenerated conversion function.
func Convert_v1alpha1_ClusterDeploymentStatus_To_clusteroperator_ClusterDeploymentStatus(in *ClusterDeploymentStatus, out *clusteroperator.ClusterDeploymentStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterDeploymentStatus_To_clusteroperator_ClusterDeploymentStatus(in, out, s)
}

func autoConvert_clusteroperator_ClusterDeploymentStatus_To_v1alpha1_ClusterDeploymentStatus(in *clusteroperator.ClusterDeploymentStatus, out *ClusterDeploymentStatus, s conversion.Scope) error {
	out.MachineSetCount = in.MachineSetCount
	out.MasterMachineSetName = in.MasterMachineSetName
	out.InfraMachineSetName = in.InfraMachineSetName
	out.AdminKubeconfig = (*core_v1.LocalObjectReference)(unsafe.Pointer(in.AdminKubeconfig))
	out.Provisioned = in.Provisioned
	out.ProvisionedJobGeneration = in.ProvisionedJobGeneration
	out.ControlPlaneInstalled = in.ControlPlaneInstalled
	out.ControlPlaneInstalledJobClusterGeneration = in.ControlPlaneInstalledJobClusterGeneration
	out.ControlPlaneInstalledJobMachineSetGeneration = in.ControlPlaneInstalledJobMachineSetGeneration
	out.ComponentsInstalled = in.ComponentsInstalled
	out.ComponentsInstalledJobClusterGeneration = in.ComponentsInstalledJobClusterGeneration
	out.ComponentsInstalledJobMachineSetGeneration = in.ComponentsInstalledJobMachineSetGeneration
	out.NodeConfigInstalled = in.NodeConfigInstalled
	out.NodeConfigInstalledJobClusterGeneration = in.NodeConfigInstalledJobClusterGeneration
	out.NodeConfigInstalledJobMachineSetGeneration = in.NodeConfigInstalledJobMachineSetGeneration
	out.NodeConfigInstalledTime = (*v1.Time)(unsafe.Pointer(in.NodeConfigInstalledTime))
	out.ClusterAPIInstalled = in.ClusterAPIInstalled
	out.ClusterAPIInstalledJobClusterGeneration = in.ClusterAPIInstalledJobClusterGeneration
	out.ClusterAPIInstalledJobMachineSetGeneration = in.ClusterAPIInstalledJobMachineSetGeneration
	out.ClusterAPIInstalledTime = (*v1.Time)(unsafe.Pointer(in.ClusterAPIInstalledTime))
	out.Ready = in.Ready
	out.Conditions = *(*[]ClusterCondition)(unsafe.Pointer(&in.Conditions))
	out.ClusterVersionRef = (*core_v1.ObjectReference)(unsafe.Pointer(in.ClusterVersionRef))
	return nil
}

// Convert_clusteroperator_ClusterDeploymentStatus_To_v1alpha1_ClusterDeploymentStatus is an autogenerated conversion function.
func Convert_clusteroperator_ClusterDeploymentStatus_To_v1alpha1_ClusterDeploymentStatus(in *clusteroperator.ClusterDeploymentStatus, out *ClusterDeploymentStatus, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterDeploymentStatus_To_v1alpha1_ClusterDeploymentStatus(in, out, s)
}

func autoConvert_v1alpha1_ClusterHardwareSpec_To_clusteroperator_ClusterHardwareSpec(in *ClusterHardwareSpec, out *clusteroperator.ClusterHardwareSpec, s conversion.Scope) error {
	out.AWS = (*clusteroperator.AWSClusterSpec)(unsafe.Pointer(in.AWS))
	return nil
}

// Convert_v1alpha1_ClusterHardwareSpec_To_clusteroperator_ClusterHardwareSpec is an autogenerated conversion function.
func Convert_v1alpha1_ClusterHardwareSpec_To_clusteroperator_ClusterHardwareSpec(in *ClusterHardwareSpec, out *clusteroperator.ClusterHardwareSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterHardwareSpec_To_clusteroperator_ClusterHardwareSpec(in, out, s)
}

func autoConvert_clusteroperator_ClusterHardwareSpec_To_v1alpha1_ClusterHardwareSpec(in *clusteroperator.ClusterHardwareSpec, out *ClusterHardwareSpec, s conversion.Scope) error {
	out.AWS = (*AWSClusterSpec)(unsafe.Pointer(in.AWS))
	return nil
}

// Convert_clusteroperator_ClusterHardwareSpec_To_v1alpha1_ClusterHardwareSpec is an autogenerated conversion function.
func Convert_clusteroperator_ClusterHardwareSpec_To_v1alpha1_ClusterHardwareSpec(in *clusteroperator.ClusterHardwareSpec, out *ClusterHardwareSpec, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterHardwareSpec_To_v1alpha1_ClusterHardwareSpec(in, out, s)
}

func autoConvert_v1alpha1_ClusterMachineSet_To_clusteroperator_ClusterMachineSet(in *ClusterMachineSet, out *clusteroperator.ClusterMachineSet, s conversion.Scope) error {
	out.ShortName = in.ShortName
	if err := Convert_v1alpha1_MachineSetConfig_To_clusteroperator_MachineSetConfig(&in.MachineSetConfig, &out.MachineSetConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ClusterMachineSet_To_clusteroperator_ClusterMachineSet is an autogenerated conversion function.
func Convert_v1alpha1_ClusterMachineSet_To_clusteroperator_ClusterMachineSet(in *ClusterMachineSet, out *clusteroperator.ClusterMachineSet, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterMachineSet_To_clusteroperator_ClusterMachineSet(in, out, s)
}

func autoConvert_clusteroperator_ClusterMachineSet_To_v1alpha1_ClusterMachineSet(in *clusteroperator.ClusterMachineSet, out *ClusterMachineSet, s conversion.Scope) error {
	out.ShortName = in.ShortName
	if err := Convert_clusteroperator_MachineSetConfig_To_v1alpha1_MachineSetConfig(&in.MachineSetConfig, &out.MachineSetConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_clusteroperator_ClusterMachineSet_To_v1alpha1_ClusterMachineSet is an autogenerated conversion function.
func Convert_clusteroperator_ClusterMachineSet_To_v1alpha1_ClusterMachineSet(in *clusteroperator.ClusterMachineSet, out *ClusterMachineSet, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterMachineSet_To_v1alpha1_ClusterMachineSet(in, out, s)
}

func autoConvert_v1alpha1_ClusterProviderConfigSpec_To_clusteroperator_ClusterProviderConfigSpec(in *ClusterProviderConfigSpec, out *clusteroperator.ClusterProviderConfigSpec, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ClusterDeploymentSpec_To_clusteroperator_ClusterDeploymentSpec(&in.ClusterDeploymentSpec, &out.ClusterDeploymentSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ClusterProviderConfigSpec_To_clusteroperator_ClusterProviderConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_ClusterProviderConfigSpec_To_clusteroperator_ClusterProviderConfigSpec(in *ClusterProviderConfigSpec, out *clusteroperator.ClusterProviderConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterProviderConfigSpec_To_clusteroperator_ClusterProviderConfigSpec(in, out, s)
}

func autoConvert_clusteroperator_ClusterProviderConfigSpec_To_v1alpha1_ClusterProviderConfigSpec(in *clusteroperator.ClusterProviderConfigSpec, out *ClusterProviderConfigSpec, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_clusteroperator_ClusterDeploymentSpec_To_v1alpha1_ClusterDeploymentSpec(&in.ClusterDeploymentSpec, &out.ClusterDeploymentSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_clusteroperator_ClusterProviderConfigSpec_To_v1alpha1_ClusterProviderConfigSpec is an autogenerated conversion function.
func Convert_clusteroperator_ClusterProviderConfigSpec_To_v1alpha1_ClusterProviderConfigSpec(in *clusteroperator.ClusterProviderConfigSpec, out *ClusterProviderConfigSpec, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterProviderConfigSpec_To_v1alpha1_ClusterProviderConfigSpec(in, out, s)
}

func autoConvert_v1alpha1_ClusterProviderStatus_To_clusteroperator_ClusterProviderStatus(in *ClusterProviderStatus, out *clusteroperator.ClusterProviderStatus, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ClusterDeploymentStatus_To_clusteroperator_ClusterDeploymentStatus(&in.ClusterDeploymentStatus, &out.ClusterDeploymentStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ClusterProviderStatus_To_clusteroperator_ClusterProviderStatus is an autogenerated conversion function.
func Convert_v1alpha1_ClusterProviderStatus_To_clusteroperator_ClusterProviderStatus(in *ClusterProviderStatus, out *clusteroperator.ClusterProviderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterProviderStatus_To_clusteroperator_ClusterProviderStatus(in, out, s)
}

func autoConvert_clusteroperator_ClusterProviderStatus_To_v1alpha1_ClusterProviderStatus(in *clusteroperator.ClusterProviderStatus, out *ClusterProviderStatus, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_clusteroperator_ClusterDeploymentStatus_To_v1alpha1_ClusterDeploymentStatus(&in.ClusterDeploymentStatus, &out.ClusterDeploymentStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_clusteroperator_ClusterProviderStatus_To_v1alpha1_ClusterProviderStatus is an autogenerated conversion function.
func Convert_clusteroperator_ClusterProviderStatus_To_v1alpha1_ClusterProviderStatus(in *clusteroperator.ClusterProviderStatus, out *ClusterProviderStatus, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterProviderStatus_To_v1alpha1_ClusterProviderStatus(in, out, s)
}

func autoConvert_v1alpha1_ClusterVersion_To_clusteroperator_ClusterVersion(in *ClusterVersion, out *clusteroperator.ClusterVersion, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ClusterVersionSpec_To_clusteroperator_ClusterVersionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ClusterVersionStatus_To_clusteroperator_ClusterVersionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ClusterVersion_To_clusteroperator_ClusterVersion is an autogenerated conversion function.
func Convert_v1alpha1_ClusterVersion_To_clusteroperator_ClusterVersion(in *ClusterVersion, out *clusteroperator.ClusterVersion, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterVersion_To_clusteroperator_ClusterVersion(in, out, s)
}

func autoConvert_clusteroperator_ClusterVersion_To_v1alpha1_ClusterVersion(in *clusteroperator.ClusterVersion, out *ClusterVersion, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_clusteroperator_ClusterVersionSpec_To_v1alpha1_ClusterVersionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_clusteroperator_ClusterVersionStatus_To_v1alpha1_ClusterVersionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_clusteroperator_ClusterVersion_To_v1alpha1_ClusterVersion is an autogenerated conversion function.
func Convert_clusteroperator_ClusterVersion_To_v1alpha1_ClusterVersion(in *clusteroperator.ClusterVersion, out *ClusterVersion, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterVersion_To_v1alpha1_ClusterVersion(in, out, s)
}

func autoConvert_v1alpha1_ClusterVersionList_To_clusteroperator_ClusterVersionList(in *ClusterVersionList, out *clusteroperator.ClusterVersionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]clusteroperator.ClusterVersion)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ClusterVersionList_To_clusteroperator_ClusterVersionList is an autogenerated conversion function.
func Convert_v1alpha1_ClusterVersionList_To_clusteroperator_ClusterVersionList(in *ClusterVersionList, out *clusteroperator.ClusterVersionList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterVersionList_To_clusteroperator_ClusterVersionList(in, out, s)
}

func autoConvert_clusteroperator_ClusterVersionList_To_v1alpha1_ClusterVersionList(in *clusteroperator.ClusterVersionList, out *ClusterVersionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ClusterVersion)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_clusteroperator_ClusterVersionList_To_v1alpha1_ClusterVersionList is an autogenerated conversion function.
func Convert_clusteroperator_ClusterVersionList_To_v1alpha1_ClusterVersionList(in *clusteroperator.ClusterVersionList, out *ClusterVersionList, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterVersionList_To_v1alpha1_ClusterVersionList(in, out, s)
}

func autoConvert_v1alpha1_ClusterVersionReference_To_clusteroperator_ClusterVersionReference(in *ClusterVersionReference, out *clusteroperator.ClusterVersionReference, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_ClusterVersionReference_To_clusteroperator_ClusterVersionReference is an autogenerated conversion function.
func Convert_v1alpha1_ClusterVersionReference_To_clusteroperator_ClusterVersionReference(in *ClusterVersionReference, out *clusteroperator.ClusterVersionReference, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterVersionReference_To_clusteroperator_ClusterVersionReference(in, out, s)
}

func autoConvert_clusteroperator_ClusterVersionReference_To_v1alpha1_ClusterVersionReference(in *clusteroperator.ClusterVersionReference, out *ClusterVersionReference, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	return nil
}

// Convert_clusteroperator_ClusterVersionReference_To_v1alpha1_ClusterVersionReference is an autogenerated conversion function.
func Convert_clusteroperator_ClusterVersionReference_To_v1alpha1_ClusterVersionReference(in *clusteroperator.ClusterVersionReference, out *ClusterVersionReference, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterVersionReference_To_v1alpha1_ClusterVersionReference(in, out, s)
}

func autoConvert_v1alpha1_ClusterVersionSpec_To_clusteroperator_ClusterVersionSpec(in *ClusterVersionSpec, out *clusteroperator.ClusterVersionSpec, s conversion.Scope) error {
	out.ImageFormat = in.ImageFormat
	if err := Convert_v1alpha1_VMImages_To_clusteroperator_VMImages(&in.VMImages, &out.VMImages, s); err != nil {
		return err
	}
	out.DeploymentType = clusteroperator.ClusterDeploymentType(in.DeploymentType)
	out.Version = in.Version
	out.OpenshiftAnsibleImage = (*string)(unsafe.Pointer(in.OpenshiftAnsibleImage))
	out.OpenshiftAnsibleImagePullPolicy = (*core_v1.PullPolicy)(unsafe.Pointer(in.OpenshiftAnsibleImagePullPolicy))
	out.ClusterAPIImage = (*string)(unsafe.Pointer(in.ClusterAPIImage))
	out.ClusterAPIImagePullPolicy = (*core_v1.PullPolicy)(unsafe.Pointer(in.ClusterAPIImagePullPolicy))
	out.MachineControllerImage = (*string)(unsafe.Pointer(in.MachineControllerImage))
	out.MachineControllerImagePullPolicy = (*core_v1.PullPolicy)(unsafe.Pointer(in.MachineControllerImagePullPolicy))
	return nil
}

// Convert_v1alpha1_ClusterVersionSpec_To_clusteroperator_ClusterVersionSpec is an autogenerated conversion function.
func Convert_v1alpha1_ClusterVersionSpec_To_clusteroperator_ClusterVersionSpec(in *ClusterVersionSpec, out *clusteroperator.ClusterVersionSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterVersionSpec_To_clusteroperator_ClusterVersionSpec(in, out, s)
}

func autoConvert_clusteroperator_ClusterVersionSpec_To_v1alpha1_ClusterVersionSpec(in *clusteroperator.ClusterVersionSpec, out *ClusterVersionSpec, s conversion.Scope) error {
	out.ImageFormat = in.ImageFormat
	if err := Convert_clusteroperator_VMImages_To_v1alpha1_VMImages(&in.VMImages, &out.VMImages, s); err != nil {
		return err
	}
	out.DeploymentType = ClusterDeploymentType(in.DeploymentType)
	out.Version = in.Version
	out.OpenshiftAnsibleImage = (*string)(unsafe.Pointer(in.OpenshiftAnsibleImage))
	out.OpenshiftAnsibleImagePullPolicy = (*core_v1.PullPolicy)(unsafe.Pointer(in.OpenshiftAnsibleImagePullPolicy))
	out.ClusterAPIImage = (*string)(unsafe.Pointer(in.ClusterAPIImage))
	out.ClusterAPIImagePullPolicy = (*core_v1.PullPolicy)(unsafe.Pointer(in.ClusterAPIImagePullPolicy))
	out.MachineControllerImage = (*string)(unsafe.Pointer(in.MachineControllerImage))
	out.MachineControllerImagePullPolicy = (*core_v1.PullPolicy)(unsafe.Pointer(in.MachineControllerImagePullPolicy))
	return nil
}

// Convert_clusteroperator_ClusterVersionSpec_To_v1alpha1_ClusterVersionSpec is an autogenerated conversion function.
func Convert_clusteroperator_ClusterVersionSpec_To_v1alpha1_ClusterVersionSpec(in *clusteroperator.ClusterVersionSpec, out *ClusterVersionSpec, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterVersionSpec_To_v1alpha1_ClusterVersionSpec(in, out, s)
}

func autoConvert_v1alpha1_ClusterVersionStatus_To_clusteroperator_ClusterVersionStatus(in *ClusterVersionStatus, out *clusteroperator.ClusterVersionStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ClusterVersionStatus_To_clusteroperator_ClusterVersionStatus is an autogenerated conversion function.
func Convert_v1alpha1_ClusterVersionStatus_To_clusteroperator_ClusterVersionStatus(in *ClusterVersionStatus, out *clusteroperator.ClusterVersionStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterVersionStatus_To_clusteroperator_ClusterVersionStatus(in, out, s)
}

func autoConvert_clusteroperator_ClusterVersionStatus_To_v1alpha1_ClusterVersionStatus(in *clusteroperator.ClusterVersionStatus, out *ClusterVersionStatus, s conversion.Scope) error {
	return nil
}

// Convert_clusteroperator_ClusterVersionStatus_To_v1alpha1_ClusterVersionStatus is an autogenerated conversion function.
func Convert_clusteroperator_ClusterVersionStatus_To_v1alpha1_ClusterVersionStatus(in *clusteroperator.ClusterVersionStatus, out *ClusterVersionStatus, s conversion.Scope) error {
	return autoConvert_clusteroperator_ClusterVersionStatus_To_v1alpha1_ClusterVersionStatus(in, out, s)
}

func autoConvert_v1alpha1_MachineSetAWSHardwareSpec_To_clusteroperator_MachineSetAWSHardwareSpec(in *MachineSetAWSHardwareSpec, out *clusteroperator.MachineSetAWSHardwareSpec, s conversion.Scope) error {
	out.InstanceType = in.InstanceType
	return nil
}

// Convert_v1alpha1_MachineSetAWSHardwareSpec_To_clusteroperator_MachineSetAWSHardwareSpec is an autogenerated conversion function.
func Convert_v1alpha1_MachineSetAWSHardwareSpec_To_clusteroperator_MachineSetAWSHardwareSpec(in *MachineSetAWSHardwareSpec, out *clusteroperator.MachineSetAWSHardwareSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSetAWSHardwareSpec_To_clusteroperator_MachineSetAWSHardwareSpec(in, out, s)
}

func autoConvert_clusteroperator_MachineSetAWSHardwareSpec_To_v1alpha1_MachineSetAWSHardwareSpec(in *clusteroperator.MachineSetAWSHardwareSpec, out *MachineSetAWSHardwareSpec, s conversion.Scope) error {
	out.InstanceType = in.InstanceType
	return nil
}

// Convert_clusteroperator_MachineSetAWSHardwareSpec_To_v1alpha1_MachineSetAWSHardwareSpec is an autogenerated conversion function.
func Convert_clusteroperator_MachineSetAWSHardwareSpec_To_v1alpha1_MachineSetAWSHardwareSpec(in *clusteroperator.MachineSetAWSHardwareSpec, out *MachineSetAWSHardwareSpec, s conversion.Scope) error {
	return autoConvert_clusteroperator_MachineSetAWSHardwareSpec_To_v1alpha1_MachineSetAWSHardwareSpec(in, out, s)
}

func autoConvert_v1alpha1_MachineSetConfig_To_clusteroperator_MachineSetConfig(in *MachineSetConfig, out *clusteroperator.MachineSetConfig, s conversion.Scope) error {
	out.NodeType = clusteroperator.NodeType(in.NodeType)
	out.Infra = in.Infra
	out.Size = in.Size
	out.Hardware = (*clusteroperator.MachineSetHardwareSpec)(unsafe.Pointer(in.Hardware))
	out.NodeLabels = *(*map[string]string)(unsafe.Pointer(&in.NodeLabels))
	return nil
}

// Convert_v1alpha1_MachineSetConfig_To_clusteroperator_MachineSetConfig is an autogenerated conversion function.
func Convert_v1alpha1_MachineSetConfig_To_clusteroperator_MachineSetConfig(in *MachineSetConfig, out *clusteroperator.MachineSetConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSetConfig_To_clusteroperator_MachineSetConfig(in, out, s)
}

func autoConvert_clusteroperator_MachineSetConfig_To_v1alpha1_MachineSetConfig(in *clusteroperator.MachineSetConfig, out *MachineSetConfig, s conversion.Scope) error {
	out.NodeType = NodeType(in.NodeType)
	out.Infra = in.Infra
	out.Size = in.Size
	out.Hardware = (*MachineSetHardwareSpec)(unsafe.Pointer(in.Hardware))
	out.NodeLabels = *(*map[string]string)(unsafe.Pointer(&in.NodeLabels))
	return nil
}

// Convert_clusteroperator_MachineSetConfig_To_v1alpha1_MachineSetConfig is an autogenerated conversion function.
func Convert_clusteroperator_MachineSetConfig_To_v1alpha1_MachineSetConfig(in *clusteroperator.MachineSetConfig, out *MachineSetConfig, s conversion.Scope) error {
	return autoConvert_clusteroperator_MachineSetConfig_To_v1alpha1_MachineSetConfig(in, out, s)
}

func autoConvert_v1alpha1_MachineSetHardwareSpec_To_clusteroperator_MachineSetHardwareSpec(in *MachineSetHardwareSpec, out *clusteroperator.MachineSetHardwareSpec, s conversion.Scope) error {
	out.AWS = (*clusteroperator.MachineSetAWSHardwareSpec)(unsafe.Pointer(in.AWS))
	return nil
}

// Convert_v1alpha1_MachineSetHardwareSpec_To_clusteroperator_MachineSetHardwareSpec is an autogenerated conversion function.
func Convert_v1alpha1_MachineSetHardwareSpec_To_clusteroperator_MachineSetHardwareSpec(in *MachineSetHardwareSpec, out *clusteroperator.MachineSetHardwareSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSetHardwareSpec_To_clusteroperator_MachineSetHardwareSpec(in, out, s)
}

func autoConvert_clusteroperator_MachineSetHardwareSpec_To_v1alpha1_MachineSetHardwareSpec(in *clusteroperator.MachineSetHardwareSpec, out *MachineSetHardwareSpec, s conversion.Scope) error {
	out.AWS = (*MachineSetAWSHardwareSpec)(unsafe.Pointer(in.AWS))
	return nil
}

// Convert_clusteroperator_MachineSetHardwareSpec_To_v1alpha1_MachineSetHardwareSpec is an autogenerated conversion function.
func Convert_clusteroperator_MachineSetHardwareSpec_To_v1alpha1_MachineSetHardwareSpec(in *clusteroperator.MachineSetHardwareSpec, out *MachineSetHardwareSpec, s conversion.Scope) error {
	return autoConvert_clusteroperator_MachineSetHardwareSpec_To_v1alpha1_MachineSetHardwareSpec(in, out, s)
}

func autoConvert_v1alpha1_MachineSetProviderConfigSpec_To_clusteroperator_MachineSetProviderConfigSpec(in *MachineSetProviderConfigSpec, out *clusteroperator.MachineSetProviderConfigSpec, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MachineSetSpec_To_clusteroperator_MachineSetSpec(&in.MachineSetSpec, &out.MachineSetSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MachineSetProviderConfigSpec_To_clusteroperator_MachineSetProviderConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_MachineSetProviderConfigSpec_To_clusteroperator_MachineSetProviderConfigSpec(in *MachineSetProviderConfigSpec, out *clusteroperator.MachineSetProviderConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSetProviderConfigSpec_To_clusteroperator_MachineSetProviderConfigSpec(in, out, s)
}

func autoConvert_clusteroperator_MachineSetProviderConfigSpec_To_v1alpha1_MachineSetProviderConfigSpec(in *clusteroperator.MachineSetProviderConfigSpec, out *MachineSetProviderConfigSpec, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_clusteroperator_MachineSetSpec_To_v1alpha1_MachineSetSpec(&in.MachineSetSpec, &out.MachineSetSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_clusteroperator_MachineSetProviderConfigSpec_To_v1alpha1_MachineSetProviderConfigSpec is an autogenerated conversion function.
func Convert_clusteroperator_MachineSetProviderConfigSpec_To_v1alpha1_MachineSetProviderConfigSpec(in *clusteroperator.MachineSetProviderConfigSpec, out *MachineSetProviderConfigSpec, s conversion.Scope) error {
	return autoConvert_clusteroperator_MachineSetProviderConfigSpec_To_v1alpha1_MachineSetProviderConfigSpec(in, out, s)
}

func autoConvert_v1alpha1_MachineSetSpec_To_clusteroperator_MachineSetSpec(in *MachineSetSpec, out *clusteroperator.MachineSetSpec, s conversion.Scope) error {
	out.ClusterID = in.ClusterID
	if err := Convert_v1alpha1_MachineSetConfig_To_clusteroperator_MachineSetConfig(&in.MachineSetConfig, &out.MachineSetConfig, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ClusterHardwareSpec_To_clusteroperator_ClusterHardwareSpec(&in.ClusterHardware, &out.ClusterHardware, s); err != nil {
		return err
	}
	out.ClusterVersionRef = in.ClusterVersionRef
	if err := Convert_v1alpha1_VMImage_To_clusteroperator_VMImage(&in.VMImage, &out.VMImage, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MachineSetSpec_To_clusteroperator_MachineSetSpec is an autogenerated conversion function.
func Convert_v1alpha1_MachineSetSpec_To_clusteroperator_MachineSetSpec(in *MachineSetSpec, out *clusteroperator.MachineSetSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineSetSpec_To_clusteroperator_MachineSetSpec(in, out, s)
}

func autoConvert_clusteroperator_MachineSetSpec_To_v1alpha1_MachineSetSpec(in *clusteroperator.MachineSetSpec, out *MachineSetSpec, s conversion.Scope) error {
	out.ClusterID = in.ClusterID
	if err := Convert_clusteroperator_MachineSetConfig_To_v1alpha1_MachineSetConfig(&in.MachineSetConfig, &out.MachineSetConfig, s); err != nil {
		return err
	}
	if err := Convert_clusteroperator_ClusterHardwareSpec_To_v1alpha1_ClusterHardwareSpec(&in.ClusterHardware, &out.ClusterHardware, s); err != nil {
		return err
	}
	out.ClusterVersionRef = in.ClusterVersionRef
	if err := Convert_clusteroperator_VMImage_To_v1alpha1_VMImage(&in.VMImage, &out.VMImage, s); err != nil {
		return err
	}
	return nil
}

// Convert_clusteroperator_MachineSetSpec_To_v1alpha1_MachineSetSpec is an autogenerated conversion function.
func Convert_clusteroperator_MachineSetSpec_To_v1alpha1_MachineSetSpec(in *clusteroperator.MachineSetSpec, out *MachineSetSpec, s conversion.Scope) error {
	return autoConvert_clusteroperator_MachineSetSpec_To_v1alpha1_MachineSetSpec(in, out, s)
}

func autoConvert_v1alpha1_VMImage_To_clusteroperator_VMImage(in *VMImage, out *clusteroperator.VMImage, s conversion.Scope) error {
	out.AWSImage = (*string)(unsafe.Pointer(in.AWSImage))
	return nil
}

// Convert_v1alpha1_VMImage_To_clusteroperator_VMImage is an autogenerated conversion function.
func Convert_v1alpha1_VMImage_To_clusteroperator_VMImage(in *VMImage, out *clusteroperator.VMImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_VMImage_To_clusteroperator_VMImage(in, out, s)
}

func autoConvert_clusteroperator_VMImage_To_v1alpha1_VMImage(in *clusteroperator.VMImage, out *VMImage, s conversion.Scope) error {
	out.AWSImage = (*string)(unsafe.Pointer(in.AWSImage))
	return nil
}

// Convert_clusteroperator_VMImage_To_v1alpha1_VMImage is an autogenerated conversion function.
func Convert_clusteroperator_VMImage_To_v1alpha1_VMImage(in *clusteroperator.VMImage, out *VMImage, s conversion.Scope) error {
	return autoConvert_clusteroperator_VMImage_To_v1alpha1_VMImage(in, out, s)
}

func autoConvert_v1alpha1_VMImages_To_clusteroperator_VMImages(in *VMImages, out *clusteroperator.VMImages, s conversion.Scope) error {
	out.AWSImages = (*clusteroperator.AWSVMImages)(unsafe.Pointer(in.AWSImages))
	return nil
}

// Convert_v1alpha1_VMImages_To_clusteroperator_VMImages is an autogenerated conversion function.
func Convert_v1alpha1_VMImages_To_clusteroperator_VMImages(in *VMImages, out *clusteroperator.VMImages, s conversion.Scope) error {
	return autoConvert_v1alpha1_VMImages_To_clusteroperator_VMImages(in, out, s)
}

func autoConvert_clusteroperator_VMImages_To_v1alpha1_VMImages(in *clusteroperator.VMImages, out *VMImages, s conversion.Scope) error {
	out.AWSImages = (*AWSVMImages)(unsafe.Pointer(in.AWSImages))
	return nil
}

// Convert_clusteroperator_VMImages_To_v1alpha1_VMImages is an autogenerated conversion function.
func Convert_clusteroperator_VMImages_To_v1alpha1_VMImages(in *clusteroperator.VMImages, out *VMImages, s conversion.Scope) error {
	return autoConvert_clusteroperator_VMImages_To_v1alpha1_VMImages(in, out, s)
}
