/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	clusteroperator_v1alpha1 "github.com/openshift/cluster-operator/pkg/apis/clusteroperator/v1alpha1"
	clientset "github.com/openshift/cluster-operator/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/openshift/cluster-operator/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/openshift/cluster-operator/pkg/client/listers_generated/clusteroperator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// NodeInformer provides access to a shared informer and lister for
// Nodes.
type NodeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.NodeLister
}

type nodeInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewNodeInformer constructs a new informer for Node type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNodeInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.ClusteroperatorV1alpha1().Nodes(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.ClusteroperatorV1alpha1().Nodes(namespace).Watch(options)
			},
		},
		&clusteroperator_v1alpha1.Node{},
		resyncPeriod,
		indexers,
	)
}

func defaultNodeInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewNodeInformer(client, v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *nodeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&clusteroperator_v1alpha1.Node{}, defaultNodeInformer)
}

func (f *nodeInformer) Lister() v1alpha1.NodeLister {
	return v1alpha1.NewNodeLister(f.Informer().GetIndexer())
}
