/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package internalversion

import (
	clusteroperator "github.com/openshift/cluster-operator/pkg/apis/clusteroperator"
	internalclientset "github.com/openshift/cluster-operator/pkg/client/clientset_generated/internalclientset"
	internalinterfaces "github.com/openshift/cluster-operator/pkg/client/informers_generated/internalversion/internalinterfaces"
	internalversion "github.com/openshift/cluster-operator/pkg/client/listers_generated/clusteroperator/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// DNSZoneInformer provides access to a shared informer and lister for
// DNSZones.
type DNSZoneInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.DNSZoneLister
}

type dNSZoneInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDNSZoneInformer constructs a new informer for DNSZone type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDNSZoneInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDNSZoneInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDNSZoneInformer constructs a new informer for DNSZone type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDNSZoneInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Clusteroperator().DNSZones(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Clusteroperator().DNSZones(namespace).Watch(options)
			},
		},
		&clusteroperator.DNSZone{},
		resyncPeriod,
		indexers,
	)
}

func (f *dNSZoneInformer) defaultInformer(client internalclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDNSZoneInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dNSZoneInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&clusteroperator.DNSZone{}, f.defaultInformer)
}

func (f *dNSZoneInformer) Lister() internalversion.DNSZoneLister {
	return internalversion.NewDNSZoneLister(f.Informer().GetIndexer())
}
