/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package internalversion

import (
	clusteroperator "github.com/openshift/cluster-operator/pkg/apis/clusteroperator"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// DNSZoneLister helps list DNSZones.
type DNSZoneLister interface {
	// List lists all DNSZones in the indexer.
	List(selector labels.Selector) (ret []*clusteroperator.DNSZone, err error)
	// DNSZones returns an object that can list and get DNSZones.
	DNSZones(namespace string) DNSZoneNamespaceLister
	DNSZoneListerExpansion
}

// dNSZoneLister implements the DNSZoneLister interface.
type dNSZoneLister struct {
	indexer cache.Indexer
}

// NewDNSZoneLister returns a new DNSZoneLister.
func NewDNSZoneLister(indexer cache.Indexer) DNSZoneLister {
	return &dNSZoneLister{indexer: indexer}
}

// List lists all DNSZones in the indexer.
func (s *dNSZoneLister) List(selector labels.Selector) (ret []*clusteroperator.DNSZone, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*clusteroperator.DNSZone))
	})
	return ret, err
}

// DNSZones returns an object that can list and get DNSZones.
func (s *dNSZoneLister) DNSZones(namespace string) DNSZoneNamespaceLister {
	return dNSZoneNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// DNSZoneNamespaceLister helps list and get DNSZones.
type DNSZoneNamespaceLister interface {
	// List lists all DNSZones in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*clusteroperator.DNSZone, err error)
	// Get retrieves the DNSZone from the indexer for a given namespace and name.
	Get(name string) (*clusteroperator.DNSZone, error)
	DNSZoneNamespaceListerExpansion
}

// dNSZoneNamespaceLister implements the DNSZoneNamespaceLister
// interface.
type dNSZoneNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all DNSZones in the indexer for a given namespace.
func (s dNSZoneNamespaceLister) List(selector labels.Selector) (ret []*clusteroperator.DNSZone, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*clusteroperator.DNSZone))
	})
	return ret, err
}

// Get retrieves the DNSZone from the indexer for a given namespace and name.
func (s dNSZoneNamespaceLister) Get(name string) (*clusteroperator.DNSZone, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(clusteroperator.Resource("dnszone"), name)
	}
	return obj.(*clusteroperator.DNSZone), nil
}
