/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	boatswain_v1alpha1 "github.com/staebler/boatswain/pkg/apis/boatswain/v1alpha1"
	clientset "github.com/staebler/boatswain/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/staebler/boatswain/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/staebler/boatswain/pkg/client/listers_generated/boatswain/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// HostInformer provides access to a shared informer and lister for
// Hosts.
type HostInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.HostLister
}

type hostInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewHostInformer constructs a new informer for Host type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHostInformer(client clientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.BoatswainV1alpha1().Hosts().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.BoatswainV1alpha1().Hosts().Watch(options)
			},
		},
		&boatswain_v1alpha1.Host{},
		resyncPeriod,
		indexers,
	)
}

func defaultHostInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewHostInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *hostInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&boatswain_v1alpha1.Host{}, defaultHostInformer)
}

func (f *hostInformer) Lister() v1alpha1.HostLister {
	return v1alpha1.NewHostLister(f.Informer().GetIndexer())
}
