/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	boatswain_v1alpha1 "github.com/staebler/boatswain/pkg/apis/boatswain/v1alpha1"
	clientset "github.com/staebler/boatswain/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/staebler/boatswain/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/staebler/boatswain/pkg/client/listers_generated/boatswain/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// NodeGroupInformer provides access to a shared informer and lister for
// NodeGroups.
type NodeGroupInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.NodeGroupLister
}

type nodeGroupInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewNodeGroupInformer constructs a new informer for NodeGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNodeGroupInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.BoatswainV1alpha1().NodeGroups(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.BoatswainV1alpha1().NodeGroups(namespace).Watch(options)
			},
		},
		&boatswain_v1alpha1.NodeGroup{},
		resyncPeriod,
		indexers,
	)
}

func defaultNodeGroupInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewNodeGroupInformer(client, v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *nodeGroupInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&boatswain_v1alpha1.NodeGroup{}, defaultNodeGroupInformer)
}

func (f *nodeGroupInformer) Lister() v1alpha1.NodeGroupLister {
	return v1alpha1.NewNodeGroupLister(f.Informer().GetIndexer())
}
