// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	boatswain "github.com/staebler/boatswain/pkg/apis/boatswain"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_Cluster_To_boatswain_Cluster,
		Convert_boatswain_Cluster_To_v1alpha1_Cluster,
		Convert_v1alpha1_ClusterList_To_boatswain_ClusterList,
		Convert_boatswain_ClusterList_To_v1alpha1_ClusterList,
		Convert_v1alpha1_ClusterNodeGroup_To_boatswain_ClusterNodeGroup,
		Convert_boatswain_ClusterNodeGroup_To_v1alpha1_ClusterNodeGroup,
		Convert_v1alpha1_ClusterSpec_To_boatswain_ClusterSpec,
		Convert_boatswain_ClusterSpec_To_v1alpha1_ClusterSpec,
		Convert_v1alpha1_ClusterStatus_To_boatswain_ClusterStatus,
		Convert_boatswain_ClusterStatus_To_v1alpha1_ClusterStatus,
		Convert_v1alpha1_Node_To_boatswain_Node,
		Convert_boatswain_Node_To_v1alpha1_Node,
		Convert_v1alpha1_NodeGroup_To_boatswain_NodeGroup,
		Convert_boatswain_NodeGroup_To_v1alpha1_NodeGroup,
		Convert_v1alpha1_NodeGroupList_To_boatswain_NodeGroupList,
		Convert_boatswain_NodeGroupList_To_v1alpha1_NodeGroupList,
		Convert_v1alpha1_NodeGroupSpec_To_boatswain_NodeGroupSpec,
		Convert_boatswain_NodeGroupSpec_To_v1alpha1_NodeGroupSpec,
		Convert_v1alpha1_NodeGroupStatus_To_boatswain_NodeGroupStatus,
		Convert_boatswain_NodeGroupStatus_To_v1alpha1_NodeGroupStatus,
		Convert_v1alpha1_NodeList_To_boatswain_NodeList,
		Convert_boatswain_NodeList_To_v1alpha1_NodeList,
		Convert_v1alpha1_NodeSpec_To_boatswain_NodeSpec,
		Convert_boatswain_NodeSpec_To_v1alpha1_NodeSpec,
		Convert_v1alpha1_NodeStatus_To_boatswain_NodeStatus,
		Convert_boatswain_NodeStatus_To_v1alpha1_NodeStatus,
	)
}

func autoConvert_v1alpha1_Cluster_To_boatswain_Cluster(in *Cluster, out *boatswain.Cluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ClusterSpec_To_boatswain_ClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ClusterStatus_To_boatswain_ClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Cluster_To_boatswain_Cluster is an autogenerated conversion function.
func Convert_v1alpha1_Cluster_To_boatswain_Cluster(in *Cluster, out *boatswain.Cluster, s conversion.Scope) error {
	return autoConvert_v1alpha1_Cluster_To_boatswain_Cluster(in, out, s)
}

func autoConvert_boatswain_Cluster_To_v1alpha1_Cluster(in *boatswain.Cluster, out *Cluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_boatswain_ClusterSpec_To_v1alpha1_ClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_boatswain_ClusterStatus_To_v1alpha1_ClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_boatswain_Cluster_To_v1alpha1_Cluster is an autogenerated conversion function.
func Convert_boatswain_Cluster_To_v1alpha1_Cluster(in *boatswain.Cluster, out *Cluster, s conversion.Scope) error {
	return autoConvert_boatswain_Cluster_To_v1alpha1_Cluster(in, out, s)
}

func autoConvert_v1alpha1_ClusterList_To_boatswain_ClusterList(in *ClusterList, out *boatswain.ClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]boatswain.Cluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ClusterList_To_boatswain_ClusterList is an autogenerated conversion function.
func Convert_v1alpha1_ClusterList_To_boatswain_ClusterList(in *ClusterList, out *boatswain.ClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterList_To_boatswain_ClusterList(in, out, s)
}

func autoConvert_boatswain_ClusterList_To_v1alpha1_ClusterList(in *boatswain.ClusterList, out *ClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Cluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_boatswain_ClusterList_To_v1alpha1_ClusterList is an autogenerated conversion function.
func Convert_boatswain_ClusterList_To_v1alpha1_ClusterList(in *boatswain.ClusterList, out *ClusterList, s conversion.Scope) error {
	return autoConvert_boatswain_ClusterList_To_v1alpha1_ClusterList(in, out, s)
}

func autoConvert_v1alpha1_ClusterNodeGroup_To_boatswain_ClusterNodeGroup(in *ClusterNodeGroup, out *boatswain.ClusterNodeGroup, s conversion.Scope) error {
	out.Size = in.Size
	return nil
}

// Convert_v1alpha1_ClusterNodeGroup_To_boatswain_ClusterNodeGroup is an autogenerated conversion function.
func Convert_v1alpha1_ClusterNodeGroup_To_boatswain_ClusterNodeGroup(in *ClusterNodeGroup, out *boatswain.ClusterNodeGroup, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterNodeGroup_To_boatswain_ClusterNodeGroup(in, out, s)
}

func autoConvert_boatswain_ClusterNodeGroup_To_v1alpha1_ClusterNodeGroup(in *boatswain.ClusterNodeGroup, out *ClusterNodeGroup, s conversion.Scope) error {
	out.Size = in.Size
	return nil
}

// Convert_boatswain_ClusterNodeGroup_To_v1alpha1_ClusterNodeGroup is an autogenerated conversion function.
func Convert_boatswain_ClusterNodeGroup_To_v1alpha1_ClusterNodeGroup(in *boatswain.ClusterNodeGroup, out *ClusterNodeGroup, s conversion.Scope) error {
	return autoConvert_boatswain_ClusterNodeGroup_To_v1alpha1_ClusterNodeGroup(in, out, s)
}

func autoConvert_v1alpha1_ClusterSpec_To_boatswain_ClusterSpec(in *ClusterSpec, out *boatswain.ClusterSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ClusterNodeGroup_To_boatswain_ClusterNodeGroup(&in.MasterNodes, &out.MasterNodes, s); err != nil {
		return err
	}
	out.ComputeNodeGroups = *(*[]boatswain.ClusterNodeGroup)(unsafe.Pointer(&in.ComputeNodeGroups))
	return nil
}

// Convert_v1alpha1_ClusterSpec_To_boatswain_ClusterSpec is an autogenerated conversion function.
func Convert_v1alpha1_ClusterSpec_To_boatswain_ClusterSpec(in *ClusterSpec, out *boatswain.ClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterSpec_To_boatswain_ClusterSpec(in, out, s)
}

func autoConvert_boatswain_ClusterSpec_To_v1alpha1_ClusterSpec(in *boatswain.ClusterSpec, out *ClusterSpec, s conversion.Scope) error {
	if err := Convert_boatswain_ClusterNodeGroup_To_v1alpha1_ClusterNodeGroup(&in.MasterNodes, &out.MasterNodes, s); err != nil {
		return err
	}
	out.ComputeNodeGroups = *(*[]ClusterNodeGroup)(unsafe.Pointer(&in.ComputeNodeGroups))
	return nil
}

// Convert_boatswain_ClusterSpec_To_v1alpha1_ClusterSpec is an autogenerated conversion function.
func Convert_boatswain_ClusterSpec_To_v1alpha1_ClusterSpec(in *boatswain.ClusterSpec, out *ClusterSpec, s conversion.Scope) error {
	return autoConvert_boatswain_ClusterSpec_To_v1alpha1_ClusterSpec(in, out, s)
}

func autoConvert_v1alpha1_ClusterStatus_To_boatswain_ClusterStatus(in *ClusterStatus, out *boatswain.ClusterStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ClusterStatus_To_boatswain_ClusterStatus is an autogenerated conversion function.
func Convert_v1alpha1_ClusterStatus_To_boatswain_ClusterStatus(in *ClusterStatus, out *boatswain.ClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterStatus_To_boatswain_ClusterStatus(in, out, s)
}

func autoConvert_boatswain_ClusterStatus_To_v1alpha1_ClusterStatus(in *boatswain.ClusterStatus, out *ClusterStatus, s conversion.Scope) error {
	return nil
}

// Convert_boatswain_ClusterStatus_To_v1alpha1_ClusterStatus is an autogenerated conversion function.
func Convert_boatswain_ClusterStatus_To_v1alpha1_ClusterStatus(in *boatswain.ClusterStatus, out *ClusterStatus, s conversion.Scope) error {
	return autoConvert_boatswain_ClusterStatus_To_v1alpha1_ClusterStatus(in, out, s)
}

func autoConvert_v1alpha1_Node_To_boatswain_Node(in *Node, out *boatswain.Node, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_NodeSpec_To_boatswain_NodeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_NodeStatus_To_boatswain_NodeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Node_To_boatswain_Node is an autogenerated conversion function.
func Convert_v1alpha1_Node_To_boatswain_Node(in *Node, out *boatswain.Node, s conversion.Scope) error {
	return autoConvert_v1alpha1_Node_To_boatswain_Node(in, out, s)
}

func autoConvert_boatswain_Node_To_v1alpha1_Node(in *boatswain.Node, out *Node, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_boatswain_NodeSpec_To_v1alpha1_NodeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_boatswain_NodeStatus_To_v1alpha1_NodeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_boatswain_Node_To_v1alpha1_Node is an autogenerated conversion function.
func Convert_boatswain_Node_To_v1alpha1_Node(in *boatswain.Node, out *Node, s conversion.Scope) error {
	return autoConvert_boatswain_Node_To_v1alpha1_Node(in, out, s)
}

func autoConvert_v1alpha1_NodeGroup_To_boatswain_NodeGroup(in *NodeGroup, out *boatswain.NodeGroup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_NodeGroupSpec_To_boatswain_NodeGroupSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_NodeGroupStatus_To_boatswain_NodeGroupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_NodeGroup_To_boatswain_NodeGroup is an autogenerated conversion function.
func Convert_v1alpha1_NodeGroup_To_boatswain_NodeGroup(in *NodeGroup, out *boatswain.NodeGroup, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeGroup_To_boatswain_NodeGroup(in, out, s)
}

func autoConvert_boatswain_NodeGroup_To_v1alpha1_NodeGroup(in *boatswain.NodeGroup, out *NodeGroup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_boatswain_NodeGroupSpec_To_v1alpha1_NodeGroupSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_boatswain_NodeGroupStatus_To_v1alpha1_NodeGroupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_boatswain_NodeGroup_To_v1alpha1_NodeGroup is an autogenerated conversion function.
func Convert_boatswain_NodeGroup_To_v1alpha1_NodeGroup(in *boatswain.NodeGroup, out *NodeGroup, s conversion.Scope) error {
	return autoConvert_boatswain_NodeGroup_To_v1alpha1_NodeGroup(in, out, s)
}

func autoConvert_v1alpha1_NodeGroupList_To_boatswain_NodeGroupList(in *NodeGroupList, out *boatswain.NodeGroupList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]boatswain.NodeGroup)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_NodeGroupList_To_boatswain_NodeGroupList is an autogenerated conversion function.
func Convert_v1alpha1_NodeGroupList_To_boatswain_NodeGroupList(in *NodeGroupList, out *boatswain.NodeGroupList, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeGroupList_To_boatswain_NodeGroupList(in, out, s)
}

func autoConvert_boatswain_NodeGroupList_To_v1alpha1_NodeGroupList(in *boatswain.NodeGroupList, out *NodeGroupList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]NodeGroup)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_boatswain_NodeGroupList_To_v1alpha1_NodeGroupList is an autogenerated conversion function.
func Convert_boatswain_NodeGroupList_To_v1alpha1_NodeGroupList(in *boatswain.NodeGroupList, out *NodeGroupList, s conversion.Scope) error {
	return autoConvert_boatswain_NodeGroupList_To_v1alpha1_NodeGroupList(in, out, s)
}

func autoConvert_v1alpha1_NodeGroupSpec_To_boatswain_NodeGroupSpec(in *NodeGroupSpec, out *boatswain.NodeGroupSpec, s conversion.Scope) error {
	out.ClusterName = in.ClusterName
	out.NodeType = boatswain.NodeType(in.NodeType)
	return nil
}

// Convert_v1alpha1_NodeGroupSpec_To_boatswain_NodeGroupSpec is an autogenerated conversion function.
func Convert_v1alpha1_NodeGroupSpec_To_boatswain_NodeGroupSpec(in *NodeGroupSpec, out *boatswain.NodeGroupSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeGroupSpec_To_boatswain_NodeGroupSpec(in, out, s)
}

func autoConvert_boatswain_NodeGroupSpec_To_v1alpha1_NodeGroupSpec(in *boatswain.NodeGroupSpec, out *NodeGroupSpec, s conversion.Scope) error {
	out.ClusterName = in.ClusterName
	out.NodeType = NodeType(in.NodeType)
	return nil
}

// Convert_boatswain_NodeGroupSpec_To_v1alpha1_NodeGroupSpec is an autogenerated conversion function.
func Convert_boatswain_NodeGroupSpec_To_v1alpha1_NodeGroupSpec(in *boatswain.NodeGroupSpec, out *NodeGroupSpec, s conversion.Scope) error {
	return autoConvert_boatswain_NodeGroupSpec_To_v1alpha1_NodeGroupSpec(in, out, s)
}

func autoConvert_v1alpha1_NodeGroupStatus_To_boatswain_NodeGroupStatus(in *NodeGroupStatus, out *boatswain.NodeGroupStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_NodeGroupStatus_To_boatswain_NodeGroupStatus is an autogenerated conversion function.
func Convert_v1alpha1_NodeGroupStatus_To_boatswain_NodeGroupStatus(in *NodeGroupStatus, out *boatswain.NodeGroupStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeGroupStatus_To_boatswain_NodeGroupStatus(in, out, s)
}

func autoConvert_boatswain_NodeGroupStatus_To_v1alpha1_NodeGroupStatus(in *boatswain.NodeGroupStatus, out *NodeGroupStatus, s conversion.Scope) error {
	return nil
}

// Convert_boatswain_NodeGroupStatus_To_v1alpha1_NodeGroupStatus is an autogenerated conversion function.
func Convert_boatswain_NodeGroupStatus_To_v1alpha1_NodeGroupStatus(in *boatswain.NodeGroupStatus, out *NodeGroupStatus, s conversion.Scope) error {
	return autoConvert_boatswain_NodeGroupStatus_To_v1alpha1_NodeGroupStatus(in, out, s)
}

func autoConvert_v1alpha1_NodeList_To_boatswain_NodeList(in *NodeList, out *boatswain.NodeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]boatswain.Node)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_NodeList_To_boatswain_NodeList is an autogenerated conversion function.
func Convert_v1alpha1_NodeList_To_boatswain_NodeList(in *NodeList, out *boatswain.NodeList, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeList_To_boatswain_NodeList(in, out, s)
}

func autoConvert_boatswain_NodeList_To_v1alpha1_NodeList(in *boatswain.NodeList, out *NodeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Node)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_boatswain_NodeList_To_v1alpha1_NodeList is an autogenerated conversion function.
func Convert_boatswain_NodeList_To_v1alpha1_NodeList(in *boatswain.NodeList, out *NodeList, s conversion.Scope) error {
	return autoConvert_boatswain_NodeList_To_v1alpha1_NodeList(in, out, s)
}

func autoConvert_v1alpha1_NodeSpec_To_boatswain_NodeSpec(in *NodeSpec, out *boatswain.NodeSpec, s conversion.Scope) error {
	out.NodeGroupName = in.NodeGroupName
	out.NodeType = boatswain.NodeType(in.NodeType)
	return nil
}

// Convert_v1alpha1_NodeSpec_To_boatswain_NodeSpec is an autogenerated conversion function.
func Convert_v1alpha1_NodeSpec_To_boatswain_NodeSpec(in *NodeSpec, out *boatswain.NodeSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeSpec_To_boatswain_NodeSpec(in, out, s)
}

func autoConvert_boatswain_NodeSpec_To_v1alpha1_NodeSpec(in *boatswain.NodeSpec, out *NodeSpec, s conversion.Scope) error {
	out.NodeGroupName = in.NodeGroupName
	out.NodeType = NodeType(in.NodeType)
	return nil
}

// Convert_boatswain_NodeSpec_To_v1alpha1_NodeSpec is an autogenerated conversion function.
func Convert_boatswain_NodeSpec_To_v1alpha1_NodeSpec(in *boatswain.NodeSpec, out *NodeSpec, s conversion.Scope) error {
	return autoConvert_boatswain_NodeSpec_To_v1alpha1_NodeSpec(in, out, s)
}

func autoConvert_v1alpha1_NodeStatus_To_boatswain_NodeStatus(in *NodeStatus, out *boatswain.NodeStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_NodeStatus_To_boatswain_NodeStatus is an autogenerated conversion function.
func Convert_v1alpha1_NodeStatus_To_boatswain_NodeStatus(in *NodeStatus, out *boatswain.NodeStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeStatus_To_boatswain_NodeStatus(in, out, s)
}

func autoConvert_boatswain_NodeStatus_To_v1alpha1_NodeStatus(in *boatswain.NodeStatus, out *NodeStatus, s conversion.Scope) error {
	return nil
}

// Convert_boatswain_NodeStatus_To_v1alpha1_NodeStatus is an autogenerated conversion function.
func Convert_boatswain_NodeStatus_To_v1alpha1_NodeStatus(in *boatswain.NodeStatus, out *NodeStatus, s conversion.Scope) error {
	return autoConvert_boatswain_NodeStatus_To_v1alpha1_NodeStatus(in, out, s)
}
